<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ECOM20001 Semester 2 2025   Tutorial 12   Time Series Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style_rb.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">ECOM20001 Semester 2 2025 <br> Tutorial 12 <br> Time Series Regression</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#q1" id="toc-q1" class="nav-link" data-scroll-target="#q1">Q1</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2">Q2</a></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6">Q6</a></li>
  <li><a href="#q7" id="toc-q7" class="nav-link" data-scroll-target="#q7">Q7</a></li>
  <li><a href="#q8" id="toc-q8" class="nav-link" data-scroll-target="#q8">Q8</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>This tutorial uses the following files available on Canvas:</p>
<ul>
<li>tute12.R<br>
</li>
<li>tute12_petrol.csv</li>
</ul>
<p>The first file is the <span class="math inline">\(\texttt{R}\)</span> code for tutorial 12, the second file is the .csv file that contains the dataset for the tutorial.</p>
<p>The dataset has the following 3 variables:</p>
<table class="table">
<tbody>
<tr class="odd">
<td><em>week</em></td>
<td>week of the year in 2013, from week 1 (start of January) to week 48</td>
</tr>
<tr class="even">
<td><em>search</em></td>
<td>number of website hits on the online petrol price reporting platform [Fuelwatch: <a href="https://www.fuelwatch.wa.gov.au/%5D">https://www.fuelwatch.wa.gov.au/]</a></td>
</tr>
<tr class="odd">
<td><em>price</em></td>
<td>average retail petrol price in a week in Perth, WA</td>
</tr>
<tr class="even">
<td><em>cost</em></td>
<td>equals one if an individual is female, 0 otherwise</td>
</tr>
<tr class="odd">
<td><em>age</em></td>
<td>average wholesale petrol cost in a week in Perth, WA</td>
</tr>
</tbody>
</table>
<p>In total, the dataset contains this information for 48 weeks in 2013 in Perth.</p>
<p>Having worked through the <strong>tute12.R</strong> code and graphs, please answer the following:</p>
</section>
<section id="q1" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="q1">Q1</h2>
<p>Construct the following variables:</p>
<ul>
<li>First and second lags of search, price, and cost<br>
</li>
<li>First difference of search, price, and cost<br>
</li>
<li>First and second lags of the first difference of search, price, and cost<br>
</li>
<li>Dummy variables for the four quarters (or seasons) of the year</li>
</ul>
<p>Explain why any lags, differences, or seasonal dummies that you constructed do not have observations.</p>
<p><strong>Solution</strong></p>
<p>See the R code provided e.g.</p>

<div class="no-row-height column-margin column-container"><div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load Applied Econometrics Package for testing and heteroskedasticity robust standard errors</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER) </span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># load stargazer()</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Load dataset on consumer search and petrol prices</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>mydata<span class="ot">=</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">"tute12_petrol.csv"</span>)  </span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Re-scale search variable in terms of 10000's searches per-week</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Important for making AR(p) and ADL(p,q) models more interpretable</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>search<span class="ot">=</span>mydata<span class="sc">$</span>search<span class="sc">/</span><span class="dv">10000</span>  </span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co"># First and second lag of price</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Use View(mydata) to check that these are indeed lagged prices</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Shifts the price variable forward 1 places, fills in first data point with NA</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>price_lag1<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">head</span>(mydata<span class="sc">$</span>price, <span class="sc">-</span><span class="dv">1</span>))</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Shifts the price variable forward 2 places, fills in first data point with NA</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>price_lag2<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="fu">head</span>(mydata<span class="sc">$</span>price, <span class="sc">-</span><span class="dv">2</span>))   </span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co"># First and second lag of cost</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>cost_lag1<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">head</span>(mydata<span class="sc">$</span>cost, <span class="sc">-</span><span class="dv">1</span>))      </span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>cost_lag2<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="fu">head</span>(mydata<span class="sc">$</span>cost, <span class="sc">-</span><span class="dv">2</span>))   </span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># First and second lag of search</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>search_lag1<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">head</span>(mydata<span class="sc">$</span>search, <span class="sc">-</span><span class="dv">1</span>))      </span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>search_lag2<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="cn">NA</span>,<span class="fu">head</span>(mydata<span class="sc">$</span>search, <span class="sc">-</span><span class="dv">2</span>))   </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute first difference of price variable and its two lags</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that the "NA" part fills in "NA" for the first observation for the differenced</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="co"># variable, which we cannot compute because no value comes before the first observation</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_price<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>price))</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_price_lag1<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>price_lag1))</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_price_lag2<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>price_lag2))</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="co"># First difference of the cost variable</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_cost<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>cost))</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_cost_lag1<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>cost_lag1))</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_cost_lag2<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>cost_lag2))</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a><span class="co"># First difference of the search variable</span></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_search<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>search))</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_search_lag1<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>search_lag1))</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>d_search_lag2<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="fu">diff</span>(mydata<span class="sc">$</span>search_lag2))</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="co"># C. SEASONAL DUMMIES</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Run preliminary seasonality regressions with search, prices, costs</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a><span class="co"># Create quarterly dummy variables, week 1 is the first week of January 2018</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>sum<span class="ot">=</span><span class="fu">as.numeric</span>(mydata<span class="sc">$</span>week<span class="sc">&gt;=</span><span class="dv">1</span> <span class="sc">&amp;</span> mydata<span class="sc">$</span>week<span class="sc">&lt;=</span><span class="dv">13</span>)    <span class="co"># Summer dummy (Quarter 3)</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>aut<span class="ot">=</span><span class="fu">as.numeric</span>(mydata<span class="sc">$</span>week<span class="sc">&gt;=</span><span class="dv">14</span> <span class="sc">&amp;</span> mydata<span class="sc">$</span>week<span class="sc">&lt;=</span><span class="dv">26</span>)   <span class="co"># Autumn dummy (Quarter 4)</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>win<span class="ot">=</span><span class="fu">as.numeric</span>(mydata<span class="sc">$</span>week<span class="sc">&gt;=</span><span class="dv">27</span> <span class="sc">&amp;</span> mydata<span class="sc">$</span>week<span class="sc">&lt;=</span><span class="dv">39</span>)   <span class="co"># Winter dummy (Quarter 1)</span></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>spr<span class="ot">=</span><span class="fu">as.numeric</span>(mydata<span class="sc">$</span>week<span class="sc">&gt;=</span><span class="dv">40</span> <span class="sc">&amp;</span> mydata<span class="sc">$</span>week<span class="sc">&lt;=</span><span class="dv">52</span>)   <span class="co"># Spring dummy (Quarter 2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div><p>Check to see if the variables have been created correctly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mydata,<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  week search  price   cost price_lag1 price_lag2 cost_lag1 cost_lag2
1    1 7.5265 140.48 131.64         NA         NA        NA        NA
2    2 7.9815 141.41 131.03     140.48         NA    131.64        NA
3    3 8.0774 140.14 129.70     141.41     140.48    131.03    131.64
4    4 7.5318 139.48 129.86     140.14     141.41    129.70    131.03
5    5 7.8780 141.20 132.46     139.48     140.14    129.86    129.70
6    6 8.8418 144.90 136.16     141.20     139.48    132.46    129.86
  search_lag1 search_lag2 d_price d_price_lag1 d_price_lag2 d_cost d_cost_lag1
1          NA          NA      NA           NA           NA     NA          NA
2      7.5265          NA    0.93           NA           NA  -0.61          NA
3      7.9815      7.5265   -1.27         0.93           NA  -1.33       -0.61
4      8.0774      7.9815   -0.66        -1.27         0.93   0.16       -1.33
5      7.5318      8.0774    1.72        -0.66        -1.27   2.60        0.16
6      7.8780      7.5318    3.70         1.72        -0.66   3.70        2.60
  d_cost_lag2 d_search d_search_lag1 d_search_lag2 sum aut win spr
1          NA       NA            NA            NA   1   0   0   0
2          NA   0.4550            NA            NA   1   0   0   0
3          NA   0.0959        0.4550            NA   1   0   0   0
4       -0.61  -0.5456        0.0959        0.4550   1   0   0   0
5       -1.33   0.3462       -0.5456        0.0959   1   0   0   0
6        0.16   0.9638        0.3462       -0.5456   1   0   0   0</code></pre>
</div>
</div>
<p>Looking at the dataframe:</p>
<ul>
<li>The first lags and differences are NA for the first observation because the first observation does not have any observations before it.<br>
</li>
<li>Similar for the second lags: the second lag is NA for the second observation because there are no observations that exist two observations before it (e.g.&nbsp;before the dataset starts).<br>
</li>
<li>The third observation for the difference in the second lag does not exist because the first observation has NA for its first difference, meaning the lagged value of the first difference two periods after the first observation (e.g., the third observation) is also NA.</li>
</ul>
</section>
<section id="q2" class="level2">
<h2 class="anchored" data-anchor-id="q2">Q2</h2>
<p>Construct the following two time series plots and provide a brief interpretation of your findings:</p>
<ul>
<li>Plot 1: price and cost on the vertical axis, week on the horizontal axis<br>
</li>
<li>Plot 2: search on the vertical axis, week on the horizontal axis</li>
</ul>
<p><strong>Solution</strong></p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting retail prices and costs (note you could also do this in ggplot2() if you like)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mydata<span class="sc">$</span>week,mydata<span class="sc">$</span>price, <span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"blue"</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">120</span>,<span class="dv">160</span>),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Week"</span>,<span class="at">ylab=</span><span class="st">"Retail Price, Wholesale Cost (cpl)"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Retail Petrol Prices"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>     <span class="fu">lines</span>(mydata<span class="sc">$</span>cost, <span class="at">col =</span> <span class="st">"forestgreen"</span>,<span class="at">type=</span><span class="st">"l"</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Retail Price"</span>, <span class="st">"Wholesale Cost"</span>), </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"forestgreen"</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),<span class="at">cex =</span> <span class="fl">0.7</span>)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting web search activity</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mydata<span class="sc">$</span>week,mydata<span class="sc">$</span>search,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"red"</span>,<span class="at">xlab=</span><span class="st">"Week"</span>,<span class="at">ylab=</span><span class="st">"Total Weekly Website Hits"</span>,<span class="at">main=</span><span class="st">"Platform Website Hits"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The petrol price and cost graph shows retail prices track with costs closely week-to-week, with approximately a 10 cpl difference between the two. We also see two large spikes early in the year (Australian summer) and around week 30 of the year (North American summer), suggesting some seasonality in prices and costs.</p>
<p>The search figure highlights similar seasonal fluctuation in search activity around the times when retail price levels spike throughout the year, suggesting a link between the time series for search intensity and prices.</p>
</section>
<section id="q3" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="q3">Q3</h2>
<p>Compute autocorrelation functions for price, cost, and search and the first differences of price, cost, and search.</p>
<ul>
<li>Briefly comment on the persistence of these variables both in levels (the first 3 autocorrelations plots) and in first differences (the second 3 autocorrelations plots).<br>
</li>
<li>What does first differencing do to the autocorrelations?</li>
</ul>
<p><strong>Solution</strong></p>
<p><br></p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>ignore</strong> the first spike at <strong>lag 0</strong></p>
</div>
</div>
</div></div><div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid"></p>
</div>
</div>
</div>
<p>Looking at the correlograms (plots of the autocorrelation functions) for price,cost, and search and their first differences, we see that:</p>
<ol type="1">
<li>Both price and cost have very persistent time series with up to the fourth lag (one month of lags) having a statistically significant autocorrelation.<br>
</li>
<li>Search is also persistent, although less so with up to the third lag being statistically significant.</li>
<li>The ACFs for the first differences show that differencing removes the persistence in each respective time series, however we still find statistically significant autocorrelations for prices and costs with a one-week lag.</li>
</ol>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid"></p>
</div>
</div>
</div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="index_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid"></p>
</div>
</div>
</div>
</section>
<section id="q4" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="q4">Q4</h2>
<p>Run three separate regressions where in each respective regression the dependent variable is price, cost, and search, and where the regressors in each regression are the quarter dummy variables you constructed in question 1.</p>
<ul>
<li>Interpret the regression coefficients, and explain how you have avoided the dummy variable trap in the regressions.<br>
</li>
<li>Do your results suggest seasonal differences in the levels of any of the dependent variables?</li>
</ul>
<p><strong>Solution</strong></p>
<p>First run the regressions and then output the results using <strong>stargazer</strong></p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of observations in the time series (used below)</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>T<span class="ot">=</span><span class="dv">48</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># B. PRELIMINARY SEASONALITY REGRESSIONS</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Search seasonality regression check</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>seas1<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>cov1<span class="ot">=</span><span class="fu">vcovHC</span>(seas1, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>se1<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov1))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Prices seasonality regression check</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>seas2<span class="ot">=</span><span class="fu">lm</span>(price<span class="sc">~</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>cov2<span class="ot">=</span><span class="fu">vcovHC</span>(seas2, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>se2<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov2))</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Cost seasonality regression check</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>seas3<span class="ot">=</span><span class="fu">lm</span>(cost<span class="sc">~</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>cov3<span class="ot">=</span><span class="fu">vcovHC</span>(seas3, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>se3<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that search has been rescaled in terms of 10000 website hits to ensure well-scaled regression results.</p>
<ul>
<li>The dummy variable trap is avoided in these regressions by omitting the dummy variable for spring. So all of the coefficient estimates correspond to changes in search/price/cost in a given quarter relative to the baseline/ omitted category of spring.</li>
</ul>

<div class="no-row-height column-margin column-container"><div class="cell">

<table style="text-align:center">
<tbody><tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="3">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
search
</td>
<td>
price
</td>
<td>
cost
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Summer
</td>
<td>
0.82<sup>**</sup>
</td>
<td>
-0.64
</td>
<td>
0.37
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.38)
</td>
<td>
(1.31)
</td>
<td>
(1.24)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Autumn
</td>
<td>
0.52<sup>*</sup>
</td>
<td>
-4.75<sup>***</sup>
</td>
<td>
-3.58<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.30)
</td>
<td>
(1.47)
</td>
<td>
(1.44)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Winter
</td>
<td>
1.61<sup>***</sup>
</td>
<td>
5.56<sup>***</sup>
</td>
<td>
5.95<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.33)
</td>
<td>
(0.81)
</td>
<td>
(0.98)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
7.94<sup>***</sup>
</td>
<td>
145.61<sup>***</sup>
</td>
<td>
134.26<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.24)
</td>
<td>
(0.52)
</td>
<td>
(0.55)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
48
</td>
<td>
48
</td>
<td>
48
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.34
</td>
<td>
0.54
</td>
<td>
0.51
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.29
</td>
<td>
0.51
</td>
<td>
0.47
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error (df = 44)
</td>
<td>
0.83
</td>
<td>
3.67
</td>
<td>
3.66
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic (df = 3; 44)
</td>
<td>
7.49<sup>***</sup>
</td>
<td>
17.31<sup>***</sup>
</td>
<td>
14.97<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="4" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="3" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>

</tbody></table>
</div></div><ul>
<li><p>Interpreting the statistically significant results (at the 5% level) in the table, we find that:</p>
<ul>
<li><p>For search, which recall is in terms of 10,000 website visits on the Fuelwatch platform, there are 0.82 <span class="math inline">\(\times\)</span> 10000 = 8200 and 1.61 <span class="math inline">\(\times\)</span> 10,000= 16,100 more searchers on average in a given week in summer and winter relative to average weekly search levels in spring.</p></li>
<li><p>For petrol prices (in cpl) we find that relative to spring, petrol prices are on average 4.76 cpl lower and 5.56 cpl higher in autumn and winter, respectively.<br>
</p></li>
<li><p>Similarly, for petrol costs (in cpl), we find that relative to spring, petrol costs are on average 3.58 cpl lower and 5.92 cpl higher in autumn and winter, respectively.</p></li>
</ul></li>
<li><p>The results suggest seasonal increases in search in the (Australian) summer and winter, and respective seasonal decreases and increases in petrol prices and costs in the (Australian) autumn and winter.<br>
The winter-related seasonality in petrol prices is, in part, likely due to higher seasonal demand for petroleum during the Northern Hemisphere summer months due to higher rates of travel, and hence petrol demand. This ultimately pushes up global crude oil prices, and hence petrol retailers’ costs and prices.</p></li>
</ul>
</section>
<section id="q5" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="q5">Q5</h2>
<p>Estimate the following set of 6 time series regressions below, where search is the dependent variable in each.<br>
Briefly interpret your results in each in terms of their economic and statistical significance.<br>
Also compute the BIC and AIC for each model, and conclude which model would be chosen based on these two information criteria.</p>
<ul>
<li>AR(1) with search<br>
</li>
<li>AR(1) + seasonal dummies with search<br>
</li>
<li>AR(2) + seasonal dummies with search<br>
</li>
<li>ADL(0,2) + seasonal dummies with search and price<br>
</li>
<li>ADL(1,1) + seasonal dummies with search and price<br>
</li>
<li>ADL(1,2,2) + seasonal dummies with search, price, and cost</li>
</ul>
<p><strong>Solution</strong></p>
<p>Estimate the models (using the R code provided)</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># AR(1) model with search</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1,<span class="at">data=</span>mydata)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>cov1<span class="ot">=</span><span class="fu">vcovHC</span>(reg1, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>se1<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov1))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>K1<span class="ot">=</span><span class="dv">2</span>                             <span class="co"># Number of parameters in regression reg1</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>ssr1<span class="ot">=</span><span class="fu">sum</span>(<span class="fu">residuals</span>(reg1)<span class="sc">^</span><span class="dv">2</span>)      <span class="co"># SSR from the regression reg1</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>BIC1<span class="ot">=</span><span class="fu">log</span>(ssr1<span class="sc">/</span>T)<span class="sc">+</span>K1<span class="sc">*</span>(<span class="fu">log</span>(T)<span class="sc">/</span>T)   <span class="co"># BIC from the regression reg1</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>AIC1<span class="ot">=</span><span class="fu">log</span>(ssr1<span class="sc">/</span>T)<span class="sc">+</span>K1<span class="sc">*</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>T)   <span class="co"># BIC from the regression reg1</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co"># AR(1) model with search with seasonal dummies</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>cov2<span class="ot">=</span><span class="fu">vcovHC</span>(reg1, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>se2<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov2))</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(reg2, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(reg2, <span class="st">"HC1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

            Estimate Std. Error t value  Pr(&gt;|t|)    
(Intercept)  2.64855    1.20860  2.1914   0.03402 *  
search_lag1  0.64571    0.13922  4.6380 3.417e-05 ***
sum          0.55057    0.32839  1.6766   0.10106    
aut          0.38227    0.28985  1.3188   0.19437    
win          0.71155    0.31684  2.2458   0.03004 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>K2<span class="ot">=</span><span class="dv">5</span>                            </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>ssr2<span class="ot">=</span><span class="fu">sum</span>(<span class="fu">residuals</span>(reg2)<span class="sc">^</span><span class="dv">2</span>)     </span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>BIC2<span class="ot">=</span><span class="fu">log</span>(ssr2<span class="sc">/</span>T)<span class="sc">+</span>K2<span class="sc">*</span>(<span class="fu">log</span>(T)<span class="sc">/</span>T)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>AIC2<span class="ot">=</span><span class="fu">log</span>(ssr2<span class="sc">/</span>T)<span class="sc">+</span>K2<span class="sc">*</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>T)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co"># AR(2) model with search with seasonal dummies</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>reg3<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1<span class="sc">+</span>search_lag2<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>cov3<span class="ot">=</span><span class="fu">vcovHC</span>(reg3, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>se3<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov3))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>K3<span class="ot">=</span><span class="dv">6</span>                          </span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>ssr3<span class="ot">=</span><span class="fu">sum</span>(<span class="fu">residuals</span>(reg3)<span class="sc">^</span><span class="dv">2</span>)     </span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>BIC3<span class="ot">=</span><span class="fu">log</span>(ssr3<span class="sc">/</span>T)<span class="sc">+</span>K3<span class="sc">*</span>(<span class="fu">log</span>(T)<span class="sc">/</span>T)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>AIC3<span class="ot">=</span><span class="fu">log</span>(ssr3<span class="sc">/</span>T)<span class="sc">+</span>K3<span class="sc">*</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>T)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># D. ESTIMATE ADL(p,q) MODELS</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># ADL(0,2) model with search and price</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>reg4<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>price_lag1<span class="sc">+</span>price_lag2<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>cov4<span class="ot">=</span><span class="fu">vcovHC</span>(reg4, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>se4<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov4))</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>K4<span class="ot">=</span><span class="dv">6</span>                             </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>ssr4<span class="ot">=</span><span class="fu">sum</span>(<span class="fu">residuals</span>(reg4)<span class="sc">^</span><span class="dv">2</span>)     </span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>BIC4<span class="ot">=</span><span class="fu">log</span>(ssr4<span class="sc">/</span>T)<span class="sc">+</span>K4<span class="sc">*</span>(<span class="fu">log</span>(T)<span class="sc">/</span>T)</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>AIC4<span class="ot">=</span><span class="fu">log</span>(ssr4<span class="sc">/</span>T)<span class="sc">+</span>K4<span class="sc">*</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>T)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="co"># ADL(1,1) model with search and price</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>reg5<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1<span class="sc">+</span>price_lag1<span class="sc">+</span>price_lag2<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>cov5<span class="ot">=</span><span class="fu">vcovHC</span>(reg5, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>se5<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov5))</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>K5<span class="ot">=</span><span class="dv">7</span>                            </span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>ssr5<span class="ot">=</span><span class="fu">sum</span>(<span class="fu">residuals</span>(reg5)<span class="sc">^</span><span class="dv">2</span>)     </span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>BIC5<span class="ot">=</span><span class="fu">log</span>(ssr5<span class="sc">/</span>T)<span class="sc">+</span>K5<span class="sc">*</span>(<span class="fu">log</span>(T)<span class="sc">/</span>T)</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>AIC5<span class="ot">=</span><span class="fu">log</span>(ssr5<span class="sc">/</span>T)<span class="sc">+</span>K5<span class="sc">*</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>T)</span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="co"># E. ESTIMATE ADL(p,q1,q2) MODELS</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="co"># ADL(1,1,2) model with search, price, and cost</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>reg6<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1<span class="sc">+</span>price_lag1<span class="sc">+</span>price_lag2<span class="sc">+</span>cost_lag1<span class="sc">+</span>cost_lag2<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>cov6<span class="ot">=</span><span class="fu">vcovHC</span>(reg6, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>se6<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov6))</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>K6<span class="ot">=</span><span class="dv">9</span>                           </span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>ssr6<span class="ot">=</span><span class="fu">sum</span>(<span class="fu">residuals</span>(reg6)<span class="sc">^</span><span class="dv">2</span>)     </span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>BIC6<span class="ot">=</span><span class="fu">log</span>(ssr6<span class="sc">/</span>T)<span class="sc">+</span>K6<span class="sc">*</span>(<span class="fu">log</span>(T)<span class="sc">/</span>T)  </span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>AIC6<span class="ot">=</span><span class="fu">log</span>(ssr6<span class="sc">/</span>T)<span class="sc">+</span>K6<span class="sc">*</span>(<span class="fu">log</span>(<span class="dv">2</span>)<span class="sc">/</span>T) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>then output the results to <strong>stargazer</strong></p>
<div class="column-page">

<table style="text-align:center">
<tbody><tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="6" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="6">
Search
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
<td>
(3)
</td>
<td>
(4)
</td>
<td>
(5)
</td>
<td>
(6)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Search, Lag 1
</td>
<td>
0.78<sup>***</sup>
</td>
<td>
0.65<sup>***</sup>
</td>
<td>
0.65<sup>***</sup>
</td>
<td>
</td>
<td>
0.34<sup>*</sup>
</td>
<td>
0.44<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.14)
</td>
<td>
(0.14)
</td>
<td>
(0.21)
</td>
<td>
</td>
<td>
(0.20)
</td>
<td>
(0.18)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Search, Lag 2
</td>
<td>
</td>
<td>
</td>
<td>
-0.01
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.15)
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Price, Lag 1
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
0.28<sup>***</sup>
</td>
<td>
0.20<sup>***</sup>
</td>
<td>
0.18<sup>*</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.06)
</td>
<td>
(0.07)
</td>
<td>
(0.10)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Price, Lag 2
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-0.16<sup>***</sup>
</td>
<td>
-0.15<sup>***</sup>
</td>
<td>
0.03
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.05)
</td>
<td>
(0.05)
</td>
<td>
(0.06)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Cost, Lag 1
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
0.10
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.08)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Cost, Lag 2
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
-0.27<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
(0.07)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Summer
</td>
<td>
</td>
<td>
0.55
</td>
<td>
0.56
</td>
<td>
0.87<sup>**</sup>
</td>
<td>
0.63<sup>*</sup>
</td>
<td>
0.88<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.35)
</td>
<td>
(0.35)
</td>
<td>
(0.35)
</td>
<td>
(0.36)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Autumn
</td>
<td>
</td>
<td>
0.38
</td>
<td>
0.38
</td>
<td>
1.01<sup>***</sup>
</td>
<td>
0.64<sup>*</sup>
</td>
<td>
0.82<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.29)
</td>
<td>
(0.36)
</td>
<td>
(0.37)
</td>
<td>
(0.38)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Winter
</td>
<td>
</td>
<td>
0.71
</td>
<td>
0.72<sup>**</sup>
</td>
<td>
0.88<sup>**</sup>
</td>
<td>
0.72<sup>**</sup>
</td>
<td>
0.90<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
(0.33)
</td>
<td>
(0.35)
</td>
<td>
(0.33)
</td>
<td>
(0.37)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
1.89
</td>
<td>
2.65<sup>**</sup>
</td>
<td>
2.72<sup>**</sup>
</td>
<td>
-8.27<sup>***</sup>
</td>
<td>
-2.73
</td>
<td>
-3.86
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1.17)
</td>
<td>
(1.17)
</td>
<td>
(1.17)
</td>
<td>
(2.81)
</td>
<td>
(3.74)
</td>
<td>
(3.90)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
47
</td>
<td>
47
</td>
<td>
46
</td>
<td>
46
</td>
<td>
46
</td>
<td>
46
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.56
</td>
<td>
0.60
</td>
<td>
0.60
</td>
<td>
0.67
</td>
<td>
0.70
</td>
<td>
0.75
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.55
</td>
<td>
0.57
</td>
<td>
0.55
</td>
<td>
0.63
</td>
<td>
0.65
</td>
<td>
0.69
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.66 (df = 45)
</td>
<td>
0.64 (df = 42)
</td>
<td>
0.66 (df = 40)
</td>
<td>
0.60 (df = 40)
</td>
<td>
0.58 (df = 39)
</td>
<td>
0.54 (df = 37)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
56.35<sup>***</sup> (df = 1; 45)
</td>
<td>
16.06<sup>***</sup> (df = 4; 42)
</td>
<td>
11.96<sup>***</sup> (df = 5; 40)
</td>
<td>
16.37<sup>***</sup> (df = 5; 40)
</td>
<td>
14.90<sup>***</sup> (df = 6; 39)
</td>
<td>
13.78<sup>***</sup> (df = 8; 37)
</td>
</tr>
<tr>
<td colspan="7" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="6" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>

</tbody></table>
</div>
<p>Estimation results for each of the 6 models are presented in the table above, along with their BIC and AIC scores (see Lecture Note 9 for their formulae and interpretation of trading off model fit for model size when “scoring” a time series model).<br>
We keep with the rescaled search dependent variable in terms of 10,000 website hits.<br>
Interpreting the results for each model, we find:</p>
<ul>
<li>AR(1) with search reveals significant and larger persistence in search at a one-week lag.<br>
</li>
<li>AR(1) + seasonal dummies with search reveals that part of the persistence in search is driven by seasonality; once the seasonal dummies are in the regression to control for seasonality in search, the level of persistence in search (conditional on seasonal controls) falls.<br>
</li>
<li>AR(2) + seasonal dummies with search reveals that controlling for seasonality, only search lagged at one week has a persistent influence on current search. Twice-lagged search does not.<br>
</li>
<li>ADL(0,2) + seasonal dummies with search and price reveals prices one and two weeks lagged explain current search, as indicated by the statistically significant coefficient on the lagged prices. There’s a positive impact of lagged higher prices lagged one week on search, and a tapering, search reducing influence of higher prices lagged by two weeks.<br>
</li>
<li>ADL(1,2) + seasonal dummies with search and price reveals prices one and two weeks lagged continue to explain current search, as indicated by the statistically significant coefficient on the lagged prices.<br>
Lagged search still has a persistent effect (which is significant at the 10% level but not 5% level),but it is much smaller than what we documented in the AR(1) and AR(2) models.<br>
This highlights how omitted variable bias from not having lagged prices in the time series models was creating upward bias on the coefficient on lagged search in the AR(1) and AR(2) model.<br>
Part of the high degree of persistence in those models was driven by persistent positive impact of oneweek lagged prices.<br>
</li>
<li>ADL(1,2,2) + seasonal dummies with search, price, and cost reveals that when lagged costs are included in the model then it appears that lagged prices have smaller magnitude impacts on current search, while lagged costs by two weeks has a negative impact on current search levels.<br>
It is notable that the coefficient on the one-week lagged search and one-week lagged price are similar in magnitude to those from the AD(1,2) model, with the former now being statistically significant at the 5% level, and the latter being statistically significant at the 10% level (has a 0.088 p-value - see the RStudio output).<br>
This model also has the best within-sample fit in terms of RSquared.</li>
</ul>
<p>The table below reports the BIC and AIC for models (1)-(6), which is also computed in the tute12.R code.<br>
The BIC-minimising model and AIC-minimising model that this information criteria would select is model (6), the ADL(1,1,2) model.</p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>(1)</th>
<th>(2)</th>
<th>(3)</th>
<th>(4)</th>
<th>(5)</th>
<th>(6)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>BIC</td>
<td>-0.736</td>
<td>-0.611</td>
<td>-0.531</td>
<td>-0.73</td>
<td>-0.727</td>
<td><strong>-0.755</strong></td>
</tr>
<tr class="even">
<td>AIC</td>
<td>-0.869</td>
<td>-0.942</td>
<td>-0.928</td>
<td>-1.128</td>
<td>-1.191</td>
<td><strong>-1.651</strong></td>
</tr>
<tr class="odd">
<td>Adj. R-Squared</td>
<td>0.546</td>
<td>0.567</td>
<td>0.549</td>
<td>0.631</td>
<td>0.65</td>
<td>0.694</td>
</tr>
<tr class="even">
<td>Observations</td>
<td>47</td>
<td>47</td>
<td>46</td>
<td>46</td>
<td>46</td>
<td>46</td>
</tr>
</tbody>
</table>
<p><strong>Notes</strong>: Model-minimising BIC and AIC scores are highlighted in <strong>bold</strong></p>
</section>
<section id="q6" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="q6">Q6</h2>
<p>Using the ADL(1,1) + seasonal dummies you estimated in question 5, compute the predicted values from the regression, which yield the within-sample forecasts of search for each week.</p>
<ul>
<li><p>Plot your within-sample forecasts for search against the actual search values that were realised and comment on your results.<br>
Do any weeks yield particularly poor within-sample forecasts?<br>
</p></li>
<li><p>What is the sample average and standard deviation of the within-sample forecast error?</p></li>
</ul>
<p><strong>Solution</strong></p>
<p>We first need to obtain the forecasts (see the R code provided)</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. FORECASTING</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A. RE-RUN ADL REGRESSION FOR FORECASTING</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>reg5<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1<span class="sc">+</span>price_lag1<span class="sc">+</span>price_lag2<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">coeftest</span>(reg5, <span class="at">vcov =</span> <span class="fu">vcovHC</span>(reg5, <span class="st">"HC1"</span>))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co"># B. WITHIN-SAMPLE FORECASTING</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="do">## Use dataset and predict() function to generate in-sample predictions based on reg5 regression model estimates</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>search_fcast_in<span class="ot">=</span><span class="fu">predict</span>(reg5, <span class="at">data=</span>mydata) </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the within-sample forecasts and forecast errors t othe mydata dataset</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Need to make the first 2 observations in search_fcast_in "NA" because you cannot compute forecast error for first 2 observations</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="co"># due to the first and second lags of price in the regression model, which means the first and second observations</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="co"># do not have a within-sample prediction</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>search_fcast_in<span class="ot">=</span><span class="fu">c</span>(<span class="cn">NA</span>,<span class="cn">NA</span>,search_fcast_in)   </span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add forecast errors to mydata</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>mydata<span class="sc">$</span>search_fcast_in_error<span class="ot">=</span>mydata<span class="sc">$</span>search<span class="sc">-</span>mydata<span class="sc">$</span>search_fcast_in</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a><span class="do">## Output some within-sample forecasting results</span></span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Within-sample forecast for period T=48: %f"</span>, mydata<span class="sc">$</span>search_fcast_in[T])</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Within-sample forecast error for period T=48: %f"</span>, mydata<span class="sc">$</span>search_fcast_in_error[T])</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Average forecast error: %f"</span>, <span class="fu">mean</span>(mydata<span class="sc">$</span>search_fcast_in_error,<span class="at">na.rm=</span><span class="cn">TRUE</span>))         <span class="co"># Compute mean without NA data points</span></span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Std. Dev. of forecast error: %f"</span>, <span class="fu">sd</span>(mydata<span class="sc">$</span>search_fcast_in_error,<span class="at">na.rm=</span><span class="cn">TRUE</span>))      <span class="co"># Compute std. dev. without NA data points</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-warnings="false">
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept) -2.734177   3.743979 -0.7303 0.469580   
search_lag1  0.338748   0.198720  1.7047 0.096214 . 
price_lag1   0.204877   0.069311  2.9559 0.005268 **
price_lag2  -0.150128   0.050510 -2.9722 0.005045 **
sum          0.634138   0.349790  1.8129 0.077548 . 
aut          0.643659   0.366369  1.7569 0.086791 . 
win          0.724010   0.333480  2.1711 0.036073 * 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Within-sample forecast for period T=48: 8.289138"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Within-sample forecast error for period T=48: -1.867538"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Average forecast error: 0.000000"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Std. Dev. of forecast error: 0.541400"</code></pre>
</div>
</div>
<p>Then obtain the plot of actual vs.&nbsp;forecast</p>
<ul>
<li>The sample average and standard deviation of the within-sample forecast error are 0.00 cpl and 0.54 cpl, respectively. On average, the within-sample forecasts “get it right.”</li>
</ul>
<!-- -->
<ul>
<li>The weeks that have particularly poor within-sample forecasts are week 8 (forecast error = 1.17 <span class="math inline">\(\times\)</span> 10000 = 11700 searches), an underestimate of search), week 30 (forecast error = 1.21 <span class="math inline">\(\times\)</span> 10000 = 12100 searches), an underestimate of search), and week 48 (-1.87 <span class="math inline">\(\times\)</span> 10000 = -18700 searches), an overestimate of search).<br>
We can see that even though seasonality is included in the model, the model finds it hard to predict the large seasonal peaks in web search in the Australian winter and summer.</li>
</ul>
<div class="cell" data-fig.asp="0.8">
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(mydata<span class="sc">$</span>week,mydata<span class="sc">$</span>search, <span class="at">type=</span><span class="st">"l"</span>,<span class="at">col=</span><span class="st">"blue"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Week"</span>,<span class="at">ylab=</span><span class="st">"Retail Price, Forecast (cpl)"</span>,<span class="at">main=</span><span class="st">"Number of Website Searches (10000s)"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>     <span class="fu">lines</span>(mydata<span class="sc">$</span>search_fcast_in, <span class="at">col =</span> <span class="st">"orange"</span>,<span class="at">type=</span><span class="st">"l"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>     <span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"Website Hits"</span>, <span class="st">"Within-Sample Forecast"</span>), </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="fu">c</span>(<span class="st">"blue"</span>,<span class="st">"orange"</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">cex =</span> <span class="fl">0.6</span>)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="er">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></section>
<section id="q7" class="level2">
<h2 class="anchored" data-anchor-id="q7">Q7</h2>
<p>Using the ADL(1,1) + seasonal dummies model you estimated in question 5, compute the out-of-sample forecast for search in week 49 of 2013 (e.g., one week after the sample ends) and the 95% confidence interval for this forecast.</p>
<p><strong>Solution</strong></p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># OUT-OF-SAMPLE FORECASTING</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="do">## Data frame for the last observation in the sample of T=48 (defined on line 70) for generating a forfecast</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>newdata1<span class="ot">=</span><span class="fu">data.frame</span>(<span class="at">search_lag1=</span>mydata<span class="sc">$</span>search_lag1[T],<span class="at">price_lag1=</span>mydata<span class="sc">$</span>price_lag1[T],<span class="at">price_lag2=</span>mydata<span class="sc">$</span>price_lag2[T],</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">sum=</span>mydata<span class="sc">$</span>sum[T],<span class="at">aut=</span>mydata<span class="sc">$</span>aut[T],<span class="at">win=</span>mydata<span class="sc">$</span>win[T])</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Use the predict() command to forecast out the next observation in period T+1 out of the sample</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>search_fcast_out<span class="ot">=</span><span class="fu">predict</span>(reg5, <span class="at">newdata=</span>newdata1) </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Standard error of search_fcast_in_error=RMSFE (see slides 27 and 28 in Lecture Note 9)</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>RMSFE<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">var</span>(<span class="fu">residuals</span>(reg5)))</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="do">## 95% CI for out-of-sample forecast</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>search_fcast_out_CIL<span class="ot">=</span>search_fcast_out<span class="fl">-1.96</span><span class="sc">*</span>RMSFE</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>search_fcast_out_CIH<span class="ot">=</span>search_fcast_out<span class="fl">+1.96</span><span class="sc">*</span>RMSFE</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a><span class="do">## Output results</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Out-of-sample forecast for period T=49: %f"</span>, search_fcast_out)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Out-of-sample forecast for period T=49: 8.289138"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"95 CI lower bound for out-of-sample forecast: %f"</span>, search_fcast_out_CIL)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95 CI lower bound for out-of-sample forecast: 7.227995"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"95 CI upper bound for out-of-sample forecast: %f"</span>, search_fcast_out_CIH)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "95 CI upper bound for out-of-sample forecast: 9.350281"</code></pre>
</div>
</div>
<p>Using the ADL(1,1) + seasonal dummies from question 5, the out-of-sample forecast for search in week 49 of 2013 is 8.289 (or 82890 searches) with a 95% confidence interval of [7.2028, 9.350] (or [72028, 93500] searches).<br>
See the the R code for its computation, which uses the methods described in Lecture Note 9 on slide 28.</p>
</section>
<section id="q8" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="q8">Q8</h2>
<p>Using the ADL(1,2,2) + seasonal dummies with search, price, and cost model you estimated in question 5, conduct a Granger Causality test to determine whether <em>price</em> Granger causes <em>search</em>.</p>
<p><strong>Solution</strong></p>
<p>Re-estimate the ADL(1,2,2) model</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GRANGER CAUSALITY</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Re-run the ADL(1,2,2) regression</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>reg6<span class="ot">=</span><span class="fu">lm</span>(search<span class="sc">~</span>search_lag1<span class="sc">+</span>price_lag1<span class="sc">+</span>price_lag2<span class="sc">+</span>cost_lag1<span class="sc">+</span>cost_lag2<span class="sc">+</span>sum<span class="sc">+</span>aut<span class="sc">+</span>win,<span class="at">data=</span>mydata)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = search ~ search_lag1 + price_lag1 + price_lag2 + 
    cost_lag1 + cost_lag2 + sum + aut + win, data = mydata)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.87056 -0.20372 -0.00636  0.22834  1.05756 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept) -3.85989    4.78781  -0.806   0.4253  
search_lag1  0.44285    0.18249   2.427   0.0202 *
price_lag1   0.17695    0.19600   0.903   0.3724  
price_lag2   0.03313    0.08491   0.390   0.6986  
cost_lag1    0.09875    0.11744   0.841   0.4058  
cost_lag2   -0.26604    0.11587  -2.296   0.0274 *
sum          0.87738    0.33763   2.599   0.0134 *
aut          0.81921    0.35475   2.309   0.0266 *
win          0.90401    0.37482   2.412   0.0209 *
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5431 on 37 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7487,    Adjusted R-squared:  0.6943 
F-statistic: 13.78 on 8 and 37 DF,  p-value: 5.081e-09</code></pre>
</div>
</div>
<p>then we need to test for Granger causality</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Conduct the Granger Causality Test</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(reg6,<span class="fu">c</span>(<span class="st">"price_lag1=0"</span>,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>                        <span class="st">"price_lag2=0"</span>),<span class="at">vcov =</span> <span class="fu">vcovHC</span>(reg6, <span class="st">"HC1"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
price_lag1 = 0
price_lag2 = 0

Model 1: restricted model
Model 2: search ~ search_lag1 + price_lag1 + price_lag2 + cost_lag1 + 
    cost_lag2 + sum + aut + win

Note: Coefficient covariance matrix supplied.

  Res.Df Df      F  Pr(&gt;F)  
1     39                    
2     37  2 2.7014 0.08034 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>How are the degrees of freedom computed?<br>
Here, we return to slides 47-49 of the Lecture Note 10 on time series regression.</p>
<ul>
<li>df1 = 2 because price has 2 lags in the ADL model<br>
</li>
<li>df2 = 48 - max(1,2,2) - 1 - (2 + 2) - 3 - 1 = 37</li>
</ul>
<p>Notice here, unlike in slides 47-49, we also have a <strong>-3</strong> for df2 corresponding to the 3 seasonal dummy variables, <em>sum</em>, <em>aut</em>, and <em>win</em>, which are parameters that also reduce df2.</p>
</div>
</div>
</div></div><p>The null and alternative hypotheses are:</p>
<p><span class="math display">\[
\begin{align}
H_0:&amp; \beta_2=0,\beta_3=0\\
H_A: &amp; \beta_2 \neq0 \quad \text{and/or} \quad \beta_3 \neq 0
\end{align}
\]</span></p>
<p>Using the linearHypothesis() command above, yields a F-statistic of F=2.7014 with 2 and 37 degrees of freedom.<br>
The corresponding p-value for the test is 0.08, which implies that we would fail to reject the null at the 5% level. That is, according to this test, price does not Granger cause search.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>