<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ECOM20001 Semester 1 2025   Tutorial 11   Combining Logarithmic Regression and Interactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style_rb.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">ECOM20001 Semester 1 2025 <br> Tutorial 11 <br> Combining Logarithmic Regression and Interactions</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#combining-logs-and-interactions-in-a-regression" id="toc-combining-logs-and-interactions-in-a-regression" class="nav-link" data-scroll-target="#combining-logs-and-interactions-in-a-regression">Combining Logs and Interactions in a Regression</a>
  <ul class="collapse">
  <li><a href="#q1" id="toc-q1" class="nav-link" data-scroll-target="#q1">Q1</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2">Q2</a></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  </ul></li>
  <li><a href="#combining-interactions-difference-in-difference" id="toc-combining-interactions-difference-in-difference" class="nav-link" data-scroll-target="#combining-interactions-difference-in-difference">Combining Interactions: Difference-in-Difference</a>
  <ul class="collapse">
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Please create a Tutorial11 folder on your computer, and then go to the LMS site for ECOM 20001 and download the following files into the Tutorial_11 folder:</p>
<ul>
<li>tute11.R</li>
<li>tute11_cps.csv</li>
</ul>
<p>The first file is the R code for tutorial 11, the second file is the .csv file that contains the dataset for the tutorial.</p>
<p>We continue to use the U.S Current Population Survey data used in Tutorial 10 last week.</p>
<p>The dataset has the following 5 variables:</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 73%">
</colgroup>
<tbody>
<tr class="odd">
<td><em>year</em></td>
<td>year in which an individual was randomly surveyed; either 1992 or 2012</td>
</tr>
<tr class="even">
<td><em>ahe</em></td>
<td>individual’s average hourly earnings (in real terms, 2012=100)</td>
</tr>
<tr class="odd">
<td><em>bachelor</em></td>
<td>equals one if an individual has a bachelor degree, 0 otherwise</td>
</tr>
<tr class="even">
<td><em>female</em></td>
<td>equals one if an individual is female, 0 otherwise</td>
</tr>
<tr class="odd">
<td><em>age</em></td>
<td>age of the individual at the time of the survey</td>
</tr>
</tbody>
</table>
<p>In total, the dataset contains this information for 15,052 individuals in the U.S.</p>
<p>Using the R code provided, create a data set and load the required packages to complete this tutorial.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Load stargarzer package for summary statistics and regression tables</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Load Applied Econometrics Package for testing and heteroskedasticity robust standard errors</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(AER)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Load dataset </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>mydata1<span class="ot">=</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">"tute11_cps.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="combining-logs-and-interactions-in-a-regression" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="combining-logs-and-interactions-in-a-regression">Combining Logs and Interactions in a Regression</h2>
<section id="q1" class="level3">
<h3 class="anchored" data-anchor-id="q1">Q1</h3>
<p>Construct a new logarithmic variable that involves the logarithm of age interacted with the female dummy variable:</p>
<ul>
<li><code>female_log_age</code> = <code>female</code> <span class="math inline">\(\times\)</span> log(<code>age</code>)</li>
</ul>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>Run the following code:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Create logarthimic variables for ahe and age</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>log_ahe<span class="ot">=</span><span class="fu">log</span>(mydata1<span class="sc">$</span>ahe)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>log_age<span class="ot">=</span><span class="fu">log</span>(mydata1<span class="sc">$</span>age)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The as.numeric() command can be used to create dummy variables in R</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Create year of sample dummy variables for the regression</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>d1992<span class="ot">=</span><span class="fu">as.numeric</span>(mydata1<span class="sc">$</span>year<span class="sc">==</span><span class="dv">1992</span>)  </span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">#d1992 is a dummy variable that equals one if year=1992, and 0 otherwise</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>d2012<span class="ot">=</span><span class="fu">as.numeric</span>(mydata1<span class="sc">$</span>year<span class="sc">==</span><span class="dv">2012</span>)  </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">#d2012 is a dummy variable that equals one if year=2012, and 0 otherwise</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="do">## Create interactive variables involving female and age</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>female_age<span class="ot">=</span>mydata1<span class="sc">$</span>female<span class="sc">*</span>mydata1<span class="sc">$</span>age</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="do">## Create the interaction between female and log(age)</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>female_log_age<span class="ot">=</span>mydata1<span class="sc">$</span>female<span class="sc">*</span>mydata1<span class="sc">$</span>log_age</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="q2" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="q2">Q2</h3>
<p>Run the following 2 regressions, comment on the statistical significance of the coefficients involving age, female, and compute the following partial effects involving age or female:</p>
<ul>
<li>Regression 1:
<ul>
<li>Dependent variable: log_ahe<br>
</li>
<li>Independent variables: age, bachelor, female, female_age, d1992<br>
</li>
<li>Compute the following partial effects:
<ul>
<li>Partial effect of being one year older if you are male<br>
</li>
<li>Partial effect of being one year older if you are female<br>
</li>
<li>Partial effect of being female if 25 years old<br>
</li>
<li>Partial effect of being female if 30 year old</li>
</ul></li>
</ul></li>
</ul>
<p><span class="math display">\[\widehat{\log(ahe)} = \hat{\beta}_0 + \hat{\beta}_1 \, age+ \hat{\beta}_2 \, female \times age + \hat{\beta}_3 \, female + \hat{\beta}_4 \, bachelor + \hat{\beta}_5 \, d1992\]</span></p>
<ul>
<li>Regression 2:
<ul>
<li>Dependent variable: log_ahe<br>
</li>
<li>Independent variables: log_age, bachelor, female, female_log_age, 1992<br>
</li>
<li>Compute the following partial effects (elasticities because of log-log form):
<ul>
<li>Partial effect / elasticity of being one year older if you are male<br>
</li>
<li>Partial effect / elasticity of being one year older if you are female</li>
</ul></li>
</ul></li>
</ul>
<p><span class="math display">\[\widehat{\log(ahe)} = \hat{\beta}_0 + \hat{\beta}_1 \, \log(age)+ \hat{\beta}_2 \, female \times \log(age) + \hat{\beta}_3 \, female + \hat{\beta}_4 \, bachelor + \hat{\beta}_5 \, d1992\]</span></p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>run the regressions</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Regression of log(ahe) on age, allowing for differential gender effects with bachelor, + controls</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">=</span><span class="fu">lm</span>(log_ahe<span class="sc">~</span>age<span class="sc">+</span>female_age<span class="sc">+</span>female<span class="sc">+</span>bachelor<span class="sc">+</span>d1992,<span class="at">data=</span>mydata1)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>cov1<span class="ot">=</span><span class="fu">vcovHC</span>(reg1, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>se1<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov1))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Regression of log(ahe) on log(age), allowing for differential gender effects with bachelor, + controls</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>reg2<span class="ot">=</span><span class="fu">lm</span>(log_ahe<span class="sc">~</span>log_age<span class="sc">+</span>female_log_age<span class="sc">+</span>female<span class="sc">+</span>bachelor<span class="sc">+</span>d1992,<span class="at">data=</span>mydata1)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>cov2<span class="ot">=</span><span class="fu">vcovHC</span>(reg2, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>se2<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Interpreting any age, female, bachelor-related coefficients in the columns:</p>
<p>Regression 1 (or column (1) in the table, log-linear) partial effects of interest:</p>
<ul>
<li><p>Being 1 year older (change in age=1) yields a 100 x (0.031 - <code>female</code> x 1 x 0.012) percent change in average hourly earnings, <em>ahe</em></p>
<ul>
<li><p>If female (<code>female=1</code>): 1 year older yields a 100 x (0.031 - 1 x 0.012)= 1.90% increase in average hourly earnings, <em>ahe</em></p></li>
<li><p>If male (<code>female=0</code>): 1 year older yields a 100 x (0.031 - 0 x 0.012)= 3.10% increase in average hourly earnings, <em>ahe</em></p></li>
</ul></li>
</ul>

<div class="no-row-height column-margin column-container"><div class="cell">

<table style="text-align:center">
<tbody><tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td colspan="2">
Log(AHE)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(1)
</td>
<td>
(2)
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Age
</td>
<td>
0.031<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.002)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Age x Female
</td>
<td>
-0.012<sup>***</sup>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.003)
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Log(Age)
</td>
<td>
</td>
<td>
0.924<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.053)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Log(Age) x Female
</td>
<td>
</td>
<td>
-0.341<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
(0.079)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Female
</td>
<td>
0.175<sup>**</sup>
</td>
<td>
0.975<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.080)
</td>
<td>
(0.268)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Bachelor Degree
</td>
<td>
0.409<sup>***</sup>
</td>
<td>
0.409<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.008)
</td>
<td>
(0.008)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
1992 Dummy
</td>
<td>
0.038<sup>***</sup>
</td>
<td>
0.038<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.008)
</td>
<td>
(0.008)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
1.775<sup>***</sup>
</td>
<td>
-0.422<sup>**</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.054)
</td>
<td>
(0.178)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
15,052
</td>
<td>
15,052
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.190
</td>
<td>
0.191
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.190
</td>
<td>
0.190
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error (df = 15046)
</td>
<td>
0.462
</td>
<td>
0.462
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic (df = 5; 15046)
</td>
<td>
708.043<sup>***</sup>
</td>
<td>
709.088<sup>***</sup>
</td>
</tr>
<tr>
<td colspan="3" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td colspan="2" style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>

</tbody></table>
</div></div><ul>
<li><p>Being female (<code>female=1</code>) yields a partial effect of 100 x (0.175 - 1 x <code>age</code> x 0.012)</p>
<ul>
<li><p>if someone is 25 years old (<code>age=25</code>), the partial effect of being female on earnings (<code>female=1</code>) is 100 x (0.175 - 1 x 25 x 0.012) =-12.5% reduction in earnings, <em>ahe</em> relative to 25 year old males</p></li>
<li><p>if someone is 35 years old (<code>age=35</code>), the partial effect of being female on earnings (<code>female=1</code>) is 100 x (0.175 - 1 x 35 x 0.012) =-24.5% reduction in earnings, <em>ahe</em> relative to 35 year old males</p></li>
</ul></li>
<li><p>Having a bachelor’s degree (<code>bachelor=1</code>) has a partial effect of 40.9% increase in earnings, <em>ahe,</em> holding fixed age, gender, and year.</p></li>
</ul>
<p>Regression 2 (or column (2) in the table, log-log) partial effects (or in this case, elasticities) of interest:</p>
<ul>
<li><p>Being 1 year older (change in <code>age=1</code>) yields a 0.924 - 0.341 x female percent change in average hourly earnings, <em>ahe</em></p>
<ul>
<li><p>If female (<code>female=1</code>): 1% increase in age yields a 0.924 - 0.341 x 1 = 0.583% increase in average hourly earnings, <em>ahe</em>. That is, if someone is female, the elasticity of earnings with respect to age is 0.583.</p></li>
<li><p>If male (<code>female=0</code>): 1% increase in age yields a 0.924 - 0.341 x 0 = 0.924% increase in average hourly earnings, <em>ahe</em>. That is, if someone is male, the elasticity of earnings with respect to age is 0.924.</p></li>
</ul></li>
</ul>
</section>
<section id="q3" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="q3">Q3</h3>
<p>Using Regression 2, compute the elasticity of <em>ahe</em> with respect to age for females. Also report the 95% CI for this elasticity.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The predicted value from Regression 2 can be written as follows:</p>
<p><span class="math display">\[
\widehat{Y} = \widehat{log(age)} =  \hat{\beta}_{0}+\hat{\beta}_{1}log(age)+\hat{\beta}_{2}female \times log(age) + \hat{\beta}_3 female+\hat{\beta}_4 bachelor+\hat{\beta}_5d 1992
\]</span></p>
<p>Using this log-log model, a female (female=1) individual has predicted value:<br>
<span class="math display">\[\begin{align*}
\widehat{log(age)} &amp;= \hat{\beta}_0 + \hat{\beta}_1log(age) + \hat{\beta}_2 \times 1 \times log(age)+ \hat{\beta}_3 \times 1 + \hat{\beta}_4 bachelor+\hat{\beta}_5d 1992\\
  &amp; =  \hat{\beta}_0 + \left(\hat{\beta}_1 + \hat{\beta}_2  \right)log(age) + \hat{\beta}_3 + \hat{\beta}_4 bachelor+\hat{\beta}_5d 1992
\end{align*}\]</span></p>
<p>which implies that the elasticity of <em>ahe</em> the with respect to age for females is the sum of the coefficients on log(age).</p>
<p>Computing this partial effect/elasticity based on the estimated coefficients from column (2) of the table in question 7 we obtain an elasticity of: 0.924-0.341=0.583.</p>
<p>Again following the general approach to computing standard errors for nonlinear effects on slides 16-24 of lecture note 8, we can obtain the F-statistic from the following joint test based on the elasticity for females that we just derived:</p>
<p><span class="math inline">\(H_0: \beta_1+\beta_2=0 \qquad H_1: \beta_1+\beta_2 \neq0\)</span></p>
<p>This test yields an F-statistic of 97.439</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Ftest<span class="ot">=</span><span class="fu">linearHypothesis</span>(reg2,<span class="fu">c</span>(<span class="st">"log_age+female_log_age=0"</span>),<span class="at">vcov =</span> <span class="fu">vcovHC</span>(reg2, <span class="st">"HC1"</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="do">## Recover the Fstat from the joint test results in Ftest</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>Fstat<span class="ot">=</span>Ftest[<span class="dv">2</span>,<span class="dv">3</span>]</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sprintf</span>(<span class="st">"Fstat %f"</span>, Fstat)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="do">## [1] "Fstat 97.437863"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The standard error for the partial effect/elasticity for females is then computed as:</p>
<p><span class="math inline">\(SE\left(\% \Delta\hat{Y}\right)=\dfrac{|\% \Delta \hat{Y}|}{\sqrt{F}} = \dfrac{|0.583|}{\sqrt{97.439}}=0.059\)</span></p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>we work with percent changes in Y and not just changes in Y in computing the standard error because of the interpretation of the log-log specification; the partial effects are in terms of the percentage change in Y (<em>ahe</em>) associated with a percentage change in X (<em>age</em>).</p>
</div>
</div>
</div></div><p>which implies that the 95% CI for the elasticity of <em>ahe</em> the with respect to age for females is [0.583-1.96 x 0.059 , 0.583-1.96 x 0.059] = [0.467, 0.699].</p>
</section>
</section>
<section id="combining-interactions-difference-in-difference" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="combining-interactions-difference-in-difference">Combining Interactions: Difference-in-Difference</h2>
<blockquote class="blockquote">
<p>Recall that in Tutorial 10 we saw a difference-in-differences (DiD) model with Regression 6 of that tutorial which quantified the differential impact of a Bachelor’s degree on earnings between females and males.</p>
<p>Here, we consider another DiD model, this time looking at whether the impact of a Bachelor’s degree on earnings has had a differential impact over time.</p>
</blockquote>
<section id="q4" class="level3">
<h3 class="anchored" data-anchor-id="q4">Q4</h3>
<p>First, construct the following interactive variable</p>
<p>• bachelor_d2012 = bachelor x d2012</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Create logarthimic variables for ahe and age</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>mydata1<span class="sc">$</span>bachelor_d2012<span class="ot">=</span>mydata1<span class="sc">$</span>bachelor<span class="sc">*</span>mydata1<span class="sc">$</span>d2012</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="q5" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="q5">Q5</h3>
<p>Now run the following regression and interpret the magnitude and statistical significance of the coefficient estimate on bachelor_d2012:</p>
<p>• Regression 3:<br>
• Dependent variable: log_ahe<br>
• Independent variables: bachelor, female, age, d2012, bachelor_d2012</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>estimate the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## DiD regression of log(ahe) </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>reg3<span class="ot">=</span><span class="fu">lm</span>(log_ahe<span class="sc">~</span>bachelor<span class="sc">+</span>d2012<span class="sc">+</span>bachelor_d2012<span class="sc">+</span>female<span class="sc">+</span>age,<span class="at">data=</span>mydata1)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>cov3<span class="ot">=</span><span class="fu">vcovHC</span>(reg3, <span class="at">type =</span> <span class="st">"HC1"</span>)    </span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>se3<span class="ot">=</span><span class="fu">sqrt</span>(<span class="fu">diag</span>(cov3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>output to <strong>stargazer</strong></p>

<table style="text-align:center">
<tbody><tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
<em>Dependent variable:</em>
</td>
</tr>
<tr>
<td>
</td>
<td colspan="1" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
Log(AHE)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Bachelor Degree
</td>
<td>
0.385<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.010)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
2012 Dummy
</td>
<td>
-0.062<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.010)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Bachelor Degree X 2012 Dummy
</td>
<td>
0.051<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.015)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Female
</td>
<td>
-0.179<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.008)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Age
</td>
<td>
0.026<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.001)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align:left">
Constant
</td>
<td>
1.976<sup>***</sup>
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
(0.041)
</td>
</tr>
<tr>
<td style="text-align:left">
</td>
<td>
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
Observations
</td>
<td>
15,052
</td>
</tr>
<tr>
<td style="text-align:left">
R<sup>2</sup>
</td>
<td>
0.190
</td>
</tr>
<tr>
<td style="text-align:left">
Adjusted R<sup>2</sup>
</td>
<td>
0.190
</td>
</tr>
<tr>
<td style="text-align:left">
Residual Std. Error
</td>
<td>
0.462 (df = 15046)
</td>
</tr>
<tr>
<td style="text-align:left">
F Statistic
</td>
<td>
706.009<sup>***</sup> (df = 5; 15046)
</td>
</tr>
<tr>
<td colspan="2" style="border-bottom: 1px solid black">
</td>
</tr>
<tr>
<td style="text-align:left">
<em>Note:</em>
</td>
<td style="text-align:right">
<sup><em></em></sup><em>p&lt;0.1; <sup><strong></strong></sup><strong>p&lt;0.05; <sup></sup></strong></em>p&lt;0.01
</td>
</tr>

</tbody></table>
<p>Interpreting the results, holding other factors fixed, the statistically-significant 0.385 coefficient estimate on bachelor implies that earnings among individuals with a bachelor’s degree is 38.5% higher on average than those without a bachelor’s degree.</p>
<p>The statistically significant 0.051 coefficient estimate on bachelor_d2012 implies that in 2012 this earnings premium on a bachelor’s education in 2012 incrementally rises by an additional another 5.1%.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">

</div>
</div><div class="callout-margin-content">
<p>Remember, the dependent variable is in logs, so we have a log-linear specification here.</p>
<p><br><br></p>
<p>We could have alternatively developed this analysis identically using the d1992 variable instead. With the specification we work with, the difference-in-differences coefficient on bachelor_d2012 has a direct interpretation of the incremental value of a bachelor’s degree on earnings in 2012 relative to its value in 1992.</p>
<p>But we could have obtained an identical analysis working with d1992 and analogously-defined bachelor_d2012 instead.</p>
</div>
</div></div><p>That is, the bachelor’s earnings premium in 1992 is 38.5% and it grows to 38.5%+5.1%=43.6% in 2012.<br>
In sum, in terms of the “difference-in-differences” model (DID), this quantifies how the earnings difference between bachelor and non-bachelor degree holders (first difference) changes over time between 1992 and 2012 (second difference).</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>