<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ECOM20001 Semester 1 2025   Tutorial 4   Single Linear Regression Estimation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style_rb.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">ECOM20001 Semester 1 2025 <br> Tutorial 4 <br> Single Linear Regression Estimation</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#part-a" id="toc-part-a" class="nav-link active" data-scroll-target="#part-a">Part A</a>
  <ul class="collapse">
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link" data-scroll-target="#getting-started">Getting Started</a></li>
  </ul></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b">Part B</a></li>
  <li><a href="#earnings-and-height" id="toc-earnings-and-height" class="nav-link" data-scroll-target="#earnings-and-height">Earnings and Height</a>
  <ul class="collapse">
  <li><a href="#q1" id="toc-q1" class="nav-link" data-scroll-target="#q1">Q1</a></li>
  <li><a href="#q2" id="toc-q2" class="nav-link" data-scroll-target="#q2">Q2</a></li>
  <li><a href="#q3" id="toc-q3" class="nav-link" data-scroll-target="#q3">Q3</a></li>
  <li><a href="#q4" id="toc-q4" class="nav-link" data-scroll-target="#q4">Q4</a></li>
  <li><a href="#q5" id="toc-q5" class="nav-link" data-scroll-target="#q5">Q5</a></li>
  <li><a href="#q6" id="toc-q6" class="nav-link" data-scroll-target="#q6">Q6</a></li>
  </ul></li>
  <li><a href="#trade-and-growth" id="toc-trade-and-growth" class="nav-link" data-scroll-target="#trade-and-growth">Trade and Growth</a>
  <ul class="collapse">
  <li><a href="#q1-1" id="toc-q1-1" class="nav-link" data-scroll-target="#q1-1">Q1</a></li>
  <li><a href="#q2-1" id="toc-q2-1" class="nav-link" data-scroll-target="#q2-1">Q2</a></li>
  <li><a href="#q3-1" id="toc-q3-1" class="nav-link" data-scroll-target="#q3-1">Q3</a></li>
  <li><a href="#q4-1" id="toc-q4-1" class="nav-link" data-scroll-target="#q4-1">Q4</a></li>
  <li><a href="#q5-1" id="toc-q5-1" class="nav-link" data-scroll-target="#q5-1">Q5</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="part-a" class="level2">
<h2 class="anchored" data-anchor-id="part-a">Part A</h2>
<section id="getting-started" class="level3">
<h3 class="anchored" data-anchor-id="getting-started">Getting Started</h3>
<p>Please create a Tutorial4 folder on your computer, and then go to the LMS site for ECOM20001 and download the following files into the Tutorial4 folder:</p>
<ul>
<li><p><strong>tute4.R</strong></p></li>
<li><p><strong>tute4_height.csv</strong></p></li>
<li><p><strong>tute4_growth.csv</strong></p></li>
</ul>
<p>The first file is the R code for tutorial 4, the second two files are the .csv files that contain two separate datasets for the tutorial.</p>
<p>The first (micro) dataset, <strong>tute4_height.csv</strong>, has the following 6 variables:</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 78%">
</colgroup>
<tbody>
<tr class="odd">
<td><em>id</em></td>
<td>worker identifier</td>
</tr>
<tr class="even">
<td><em>earnings</em></td>
<td>annual labour earnings in $10,000’a (in real terms, 2012=100)</td>
</tr>
<tr class="odd">
<td><em>height</em></td>
<td>height without shoes in centimetres</td>
</tr>
<tr class="even">
<td><em>weight</em></td>
<td>weight without shoes in centimetres</td>
</tr>
<tr class="odd">
<td><em>male</em></td>
<td>binary variable that equals 1 if the worker is male; 0 otherwise</td>
</tr>
<tr class="even">
<td><em>age</em></td>
<td>age of the worker at the time of the survey</td>
</tr>
</tbody>
</table>
<p>In total, the dataset contains this information for n=17,870 U.S. workers.</p>
<p>The second (macro) dataset, <strong>tute4_growth.csv</strong>, has the following 4 variables:</p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 83%">
</colgroup>
<tbody>
<tr class="odd">
<td><em>country</em></td>
<td>country name</td>
</tr>
<tr class="even">
<td><em>growth</em></td>
<td>average annual percentage growth rate of real GDP (1960=100) from 1960-1995</td>
</tr>
<tr class="odd">
<td><em>rgdp60</em></td>
<td>the value of GDP per capita in 1960 (in real terms, 1960=100)</td>
</tr>
<tr class="even">
<td><em>tradeshare</em></td>
<td>the average share of annual trade in the economy from 1960 to 1995, measured as the sum of gross exports plus gross imports divided by nominal GDP; that is, the average of (X+M)/GDP from 1960 to 1995</td>
</tr>
</tbody>
</table>
<p>With the R file and data downloaded into your Tutorial4 folder, you are ready to proceed with the tutorial.<br>
Please go to the <em>tute4.R</em> file to with this tutorial.</p>
<p>The first thing to do is set the Working Directory and then load the CSV file into a dataframe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Set the working directory for the tutorial file</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#..........................</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the top menu bar option</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#..........................</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the dataset from a comma separate value</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">"tute4_height.csv"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Load required package(s)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="part-b" class="level2">
<h2 class="anchored" data-anchor-id="part-b">Part B</h2>
<p>Having worked through the tute2.R code and graphs, please answer the following:</p>
</section>
<section id="earnings-and-height" class="level2">
<h2 class="anchored" data-anchor-id="earnings-and-height">Earnings and Height</h2>
<section id="q1" class="level3">
<h3 class="anchored" data-anchor-id="q1">Q1</h3>
<p>Discuss the summary statistics for the variables in the sample. What does a typical worker look like?</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div class="cell">

</div>
<div data-align="center">
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(data1, </span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">summary.stat =</span> <span class="fu">c</span>(<span class="st">"n"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"median"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>),  </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">type=</span><span class="st">"text"</span>, <span class="at">title=</span><span class="st">"Descriptive Statistics"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Descriptive Statistics
=========================================================
Statistic   N      Mean    St. Dev.  Median   Min   Max  
---------------------------------------------------------
id        17,870 8,935.500 5,158.769 8,935.5   1   17,870
earnings  17,870   4.688     2.692    3.893  0.473 8.405 
height    17,870  170.098   10.097     170    122   213  
weight    17,870  77.356    23.323     74     36    227  
male      17,870   0.442     0.497      0      0     1   
age       17,870  40.920    10.038     40     25     65  
---------------------------------------------------------</code></pre>
</div>
</div>
</div>
<details>
<summary>
Interpretation
</summary>
<p>
</p><p>A typical worker earns $46,880 per year, is 170 cm tall, 77 kilograms and is 41 years old.<br>
44.2% of the workers in the sample are male.<br>
</p>
<p>
</p></details></section>
<section id="q2" class="level3">
<h3 class="anchored" data-anchor-id="q2">Q2</h3>
<p>Present the scatter <strong>plot q1_scat_height_earnings.pdf</strong> and discuss whether there is a relationship visually between height and earnings.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The scatter plot stored in <strong>plot q1_scat_height_earnings.pdf</strong> is reproduced below.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data1<span class="sc">$</span>height,data1<span class="sc">$</span>earnings,</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Relationship Between Height and Earnings"</span>,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Height in Centimeters"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Annual Earnings in $10,000's"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"blue"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatter plot does not immediately suggest a positive relationship between earnings and height.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Sample correlation between height and earnings</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="do">## using the cor() function</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(data1<span class="sc">$</span>height,data1<span class="sc">$</span>earnings)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1044771</code></pre>
</div>
</div>
</section>
<section id="q3" class="level3">
<h3 class="anchored" data-anchor-id="q3">Q3</h3>
<p>Compute the difference in means for workers greater and less than 170cm, conduct a two-sample t-test of the null that the difference in means is 0, and report the 95% CI for the difference in means.<br>
Do the results provide evidence of a relationship between earnings and height?</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>Run the following R code chunk</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Mean earnings for heights above and below 170cm</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data1<span class="sc">$</span>earnings[data1<span class="sc">$</span>height<span class="sc">&gt;=</span><span class="dv">170</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.909318</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data1<span class="sc">$</span>earnings[data1<span class="sc">$</span>height<span class="sc">&lt;</span><span class="dv">170</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.44879</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Difference in means for people taller and shorter than 170cm</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(data1<span class="sc">$</span>earnings[data1<span class="sc">$</span>height<span class="sc">&gt;=</span><span class="dv">170</span>])<span class="sc">-</span><span class="fu">mean</span>(data1<span class="sc">$</span>earnings[data1<span class="sc">$</span>height<span class="sc">&lt;</span><span class="dv">170</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.460528</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## 2-sample t-test of difference in means for people taller and shorter than 170cm </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(data1<span class="sc">$</span>earnings[data1<span class="sc">$</span>height<span class="sc">&gt;=</span><span class="dv">170</span>],data1<span class="sc">$</span>earnings[data1<span class="sc">$</span>height<span class="sc">&lt;</span><span class="dv">170</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  data1$earnings[data1$height &gt;= 170] and data1$earnings[data1$height &lt; 170]
t = 11.469, df = 17783, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 0.3818203 0.5392357
sample estimates:
mean of x mean of y 
 4.909318  4.448790 </code></pre>
</div>
</div>
<p>The difference in means is $4605/year.<br>
A two-sample t-test rejects the null of equal means with a t-statistic of 11.470 and p-value less than 2.2e-16.<br>
The 95% CI is [$3818,$5392].<br>
The results provide initial evidence that taller people in the top half of the sample above the median height of 170cm have higher average income than people in the bottom half of the sample with height below 170cm.</p>
</section>
<section id="q4" class="level3">
<h3 class="anchored" data-anchor-id="q4">Q4</h3>
<p>Estimate the following single linear regression model for worker <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[Earnings_i = \beta_0 + \beta_1 \, Height_i + u_i   \]</span> Provide an interpretation of the slope coefficient for a one-unit increase in height, and report the R-Squared and Standard Error of the Regression.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Single linear regression of earnings on height</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>earn_reg1<span class="ot">=</span><span class="fu">lm</span>(earnings<span class="sc">~</span>height,<span class="at">data=</span>data1)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(earn_reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = earnings ~ height, data = data1)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.7972 -2.1909 -0.7923  3.4421  5.0579 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.051174   0.338050  -0.151     0.88    
height       0.027859   0.001984  14.042   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.678 on 17868 degrees of freedom
Multiple R-squared:  0.01092,   Adjusted R-squared:  0.01086 
F-statistic: 197.2 on 1 and 17868 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(data1<span class="sc">$</span>height)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10.09693</code></pre>
</div>
</div>
<p>Reporting The regression results from the R output above we have</p>
<p><span class="math display">\[\begin{align*}
    \widehat{Earnings} &amp; = \underset{(0.338)}{-0.051}+ \underset{(0.002)}{0.028} \,height \, \underset{\qquad(s.e)}{}\\
    &amp; R^2=0.011 \qquad SER=2.678
\end{align*}\]</span></p>
<p>Increasing height by 1cm has a corresponding increase in annual earnings of $280.</p>
<p>Note the the regression results shown above include standard errors for the regression coefficient estimates as prescribed later in Lecture note 5, for consistency in presentation of results (we do not have to use these<span class="math inline">\(\dots\)</span>yet).</p>
</section>
<section id="q5" class="level3">
<h3 class="anchored" data-anchor-id="q5">Q5</h3>
<p>Provide an alternative interpretation for the regression results.</p>
<ul>
<li><p>For a worker with average height, what is the impact of increasing their height by one standard deviation on earnings?</p></li>
<li><p>How does this predicted increase compare to the sample mean of earnings?</p></li>
<li><p>Is this a more relevant interpretation of the results than the interpretation given in question 4 above? Why or why not?</p></li>
</ul>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>Average height is 170cm and the standard deviation of height 10.10cm. So, increasing height from 170cm to 180.10cm would yield a corresponding increase in earnings of $10,000 x 0.028 x 10.10cm=$2,828/year.<br>
This compares to an average earnings of $46,875/year, implying an annual earnings increase that is 100 / 46875 = 6.03% of the sample average.<br>
Given inflation tends to be in the 2 to 3% range, this implies a near doubling of income growth year-to-year relative to inflation, which could be interpreted as being economically meaningful, simply from being taller!</p>
<blockquote class="blockquote">
<p>This is a more meaningful interpretation than one based on a one-unit increase of 1 cm for a few reasons:</p>
</blockquote>
<ul>
<li><p>A 1-standard deviation increase is a “standard” degree of variation in height in the data relative to the mean so it is more typical in terms of magnitude of variation in height than just a 1cm height increase from question 4</p></li>
<li><p>Comparing the regression results relative to the mean of earnings provides a natural scaling of the results that can be used to get a sense of percentage impacts relative to the average person in the sample. Again, this permits an interpretation of the empirical results for a “typical” worker in the sample.</p></li>
<li><p>Therefore, interpretation of empirical results for regressions in terms of simple one-unit increases (1cm height increase) is not always desirable; it depends on the scale of the dependent and independent variables in a regression.</p></li>
</ul>
</section>
<section id="q6" class="level3">
<h3 class="anchored" data-anchor-id="q6">Q6</h3>
<p>Run the earnings-height regression separately for males and females.<br>
Interpret the slope coefficients in both regressions and propose a possible economic explanation for your findings.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Single linear regression of earnings on height among males</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>earn_reg2<span class="ot">=</span><span class="fu">lm</span>(earnings[male<span class="sc">==</span><span class="dv">1</span>]<span class="sc">~</span>height[male<span class="sc">==</span><span class="dv">1</span>],<span class="at">data=</span>data1)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(earn_reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = earnings[male == 1] ~ height[male == 1], data = data1)

Residuals:
   Min     1Q Median     3Q    Max 
-5.043 -2.247 -0.798  3.302  5.933 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       -4.33684    0.70920  -6.115 1.01e-09 ***
height[male == 1]  0.05158    0.00398  12.960  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.667 on 7894 degrees of freedom
Multiple R-squared:  0.02083,   Adjusted R-squared:  0.02071 
F-statistic:   168 on 1 and 7894 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Single linear regression of earnings on height among females</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>earn_reg3<span class="ot">=</span><span class="fu">lm</span>(earnings[male<span class="sc">==</span><span class="dv">0</span>]<span class="sc">~</span>height[male<span class="sc">==</span><span class="dv">0</span>],<span class="at">data=</span>data1)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(earn_reg3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = earnings[male == 0] ~ height[male == 0], data = data1)

Residuals:
   Min     1Q Median     3Q    Max 
-4.279 -2.209 -0.754  3.658  4.690 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       1.245152   0.630158   1.976   0.0482 *  
height[male == 0] 0.020246   0.003843   5.268  1.4e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.68 on 9972 degrees of freedom
Multiple R-squared:  0.002776,  Adjusted R-squared:  0.002676 
F-statistic: 27.76 on 1 and 9972 DF,  p-value: 1.405e-07</code></pre>
</div>
</div>
<p>Regression results for males:</p>
<p><span class="math display">\[\begin{align*}
    \widehat{Earnings} &amp; = \underset{(0.209)}{-4.337}+ \underset{(0.004)}{0.052} \,height \, \underset{\qquad(s.e)}{}\\
    &amp; R^2=0.021 \qquad SER=2.667
\end{align*}\]</span></p>
<p>Regression results for females:</p>
<p><span class="math display">\[\begin{align*}
    \widehat{Earnings} &amp; = \underset{(0.630)}{1.245}+ \underset{(0.004)}{0.020} \,height \, \underset{\qquad(s.e)}{}\\
    &amp; R^2=0.003 \qquad SER=2.680
\end{align*}\]</span></p>
<p>Contrasting the results for males and females, there are two notable findings:</p>
<ul>
<li><p>The regression coefficient is more than double for males. This means, for example, a one-standard deviation increase in height of 10.10 cm implies a $10,000 x 0.052 x 10.10cm=$5,200/year income increase for males compared to a $10,000 x 0.020 x 10.10cm=$2,000/year increase for females.</p></li>
<li><p>The R-Squared for the males regression of 0.021 is 7-times (!) larger than the R-Squared for the females regression of 0.003. That is, height has much more predictive power for earnings among males than females.</p></li>
</ul>
<p>One possible economic explanation for this result is men tend to work in physical jobs like manufacturing or construction where there is a benefit from being taller.</p>
<p>Another related possibility is that men historically work in more corporate jobs where being taller signals confidence and strength to other corporate types (or indeed being tall makes someone more confident because they are able to use it to their advantage in, for example sports. during their childhood), and that such signalling benefit tends to be more important for males in earning higher corporate income.</p>
<p>Note that the emerging gender shift in corporate jobs is substantial and these relationships may break down in the future as gender balance continues to improve in the corporate world.</p>
</section>
</section>
<section id="trade-and-growth" class="level2">
<h2 class="anchored" data-anchor-id="trade-and-growth">Trade and Growth</h2>
<blockquote class="blockquote">
<p>Note these are extra practice exercises and will potentially only be partially covered in the tutorial, depending on time remaining. The solutions are provided below for students to work through and follow-up in consultations if required.</p>
</blockquote>
<section id="q1-1" class="level3">
<h3 class="anchored" data-anchor-id="q1-1">Q1</h3>
<p>Discuss the summary statistics for the variables in the sample. What does a typical country look like?</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(data2, </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">summary.stat =</span> <span class="fu">c</span>(<span class="st">"n"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"median"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>),  </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">type=</span><span class="st">"text"</span>, <span class="at">title=</span><span class="st">"Descriptive Statistics"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Descriptive Statistics
=============================================================
Statistic  N    Mean    St. Dev.   Median     Min      Max   
-------------------------------------------------------------
growth     65   1.943     1.897     1.975   -2.812    7.157  
rgdp60     65 3,103.785 2,512.657 2,019.000 367.000 9,895.004
tradeshare 65   0.565     0.289     0.543    0.141    1.993  
-------------------------------------------------------------</code></pre>
</div>
</div>
<p>A typical country has an average annual growth rate of 1.94%, real (1960=100) GDP of $3,104 per person, and a trade share of 56.47%.<br>
For the latter, this means the average country gross exports and imports together more than half of its annual GDP.</p>
</section>
<section id="q2-1" class="level3">
<h3 class="anchored" data-anchor-id="q2-1">Q2</h3>
<p>Present the scatter plot <strong>q2_scat_trade_growth3.pdf</strong> and discuss whether there is a relationship visually between growth and trade.</p>
<blockquote class="blockquote">
<p>note: the graphs in questions 2 and 3 presented below are created at the bottom of the R code by combining the scatter plot command and regression results from question 4 below. See discussion in the comments of <strong>tute4.R</strong> for details</p>
</blockquote>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The scatter plot saved in <strong>q2_scat_trade_growth3.pdf</strong> is reproduced below:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="scatter_with_Malta.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>There does appear visually to be a positive relationship between growth and trade.<br>
The data point for Malta in the top right hand corner is notable.</p>
</section>
<section id="q3-1" class="level3">
<h3 class="anchored" data-anchor-id="q3-1">Q3</h3>
<p>There appears to be a potential outlier in the scatter plot from question 2 that has an average annual growth of 2.0. This country is Malta.<br>
The scatter <strong>plot q2_scat_trade_growth4.pdf</strong> drops this observation and is otherwise constructed identically to the graph in question 2.<br>
Does dropping Malta appear to have a large impact on the results?</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The scatter plot saved in <strong>q2_scat_trade_growth4.pdf</strong> is reproduced below:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="scatter_without_Malta.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the scatter plot dropping Malta ,we immediately see that the growth-trade relationship weakens as the slope of the line of best fit flattens considerably.<br>
Given the influential impact of Malta on the results, we should drop it as an outlier in the sample.</p>
</section>
<section id="q4-1" class="level3">
<h3 class="anchored" data-anchor-id="q4-1">Q4</h3>
<p>Estimate the following single linear regression using the entire sample, and for a sample that omits Malta from the data set:</p>
<p><span class="math display">\[Growth_i = \beta_0 + \beta_1\, TradeShare _i + u_i\]</span></p>
<p>For each set of results, provide an interpretation of the slope coefficient for a one unit increase in the trade share of a country, and report the R-Squared and Standard Error of the Regression .</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>Run the following R code chunks</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Regression of growth on tradeshare for entire dataset</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>growth_reg1<span class="ot">=</span><span class="fu">lm</span>(growth<span class="sc">~</span>tradeshare,<span class="at">data=</span>data2)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(growth_reg1)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="do">## Regression of growth on tradeshare exclusing potential outlier (Malta)</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>growth_reg2<span class="ot">=</span><span class="fu">lm</span>(growth[tradeshare<span class="sc">&lt;</span><span class="fu">max</span>(tradeshare)]<span class="sc">~</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>                 tradeshare[tradeshare<span class="sc">&lt;</span><span class="fu">max</span>(tradeshare)],<span class="at">data=</span>data2)</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(growth_reg2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = growth ~ tradeshare, data = data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3739 -0.8864  0.2329  0.9248  5.3889 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   0.6403     0.4900   1.307  0.19606   
tradeshare    2.3064     0.7735   2.982  0.00407 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.79 on 63 degrees of freedom
Multiple R-squared:  0.1237,    Adjusted R-squared:  0.1098 
F-statistic: 8.892 on 1 and 63 DF,  p-value: 0.00407</code></pre>
</div>
</div>
<p>Regression results for the entire sample are: <span class="math display">\[\begin{align*}
    \widehat{Growth_i} &amp; = \underset{(0.490)}{0.640} + \underset{(0.774)}{2.306}\,TradeShare_i \, \underset{\qquad(s.e)}{} \\
    &amp;  R^2=0.124, \, SER=1.790  
\end{align*}\]</span></p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = growth[tradeshare &lt; max(tradeshare)] ~ tradeshare[tradeshare &lt; 
    max(tradeshare)], data = data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.4247 -0.9383  0.2091  0.9265  5.3776 

Coefficients:
                                         Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)                                0.9574     0.5804   1.650   0.1041  
tradeshare[tradeshare &lt; max(tradeshare)]   1.6809     0.9874   1.702   0.0937 .
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.789 on 62 degrees of freedom
Multiple R-squared:  0.04466,   Adjusted R-squared:  0.02925 
F-statistic: 2.898 on 1 and 62 DF,  p-value: 0.09369</code></pre>
</div>
</div>
<p>Regression results dropping Malta are:</p>
<p><span class="math display">\[\begin{align*}
  \widehat{Growth_i} &amp; = \underset{(0.580)}{0.957} + \underset{(0.987)}{1.681}\,TradeShare_i \, \underset{\qquad(s.e)}{} \\
  &amp;  R^2=0.045, \, SER=1.789
\end{align*}\]</span></p>
<p>There is a substantial change in the regression coefficient estimate from dropping Malta from the sample.</p>
<p>In the full sample, a 1 unit 100% increase in trade share has a corresponding 2.31% increase in average annual growth rate.</p>
<p>With the sample that drops Malta, a 1 unit 100% increase in trade share has a corresponding 1.68% increase in average annual growth rate.</p>
<p>Dropping Malta from the sample reduces this estimate by 100 x (2.31-1.68)/2.31 = 27.27%, a huge change in the results. Malta should be dropped as an outlier.</p>
</section>
<section id="q5-1" class="level3">
<h3 class="anchored" data-anchor-id="q5-1">Q5</h3>
<p>Provide an alternative interpretation for the regression results based on a sample that drops Malta.<br>
For a country with average trade share, what is the impact of increasing their trade share by one standard deviation on growth?<br>
Is this effect large relative to the sample mean for growth? Provide a potential economic explanation for your findings.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The average country has a trade share of 0.5647 and the standard deviation of trade share is 0.289.</p>
<p>So increasing trade share from 0.5647 to 0.5647+0.289=0.8537 has a corresponding increase in the GDP growth rate from the results dropping Malta of 1.681 x 0.289 = 0.486% increase.</p>
<p>This is a relatively large increase relative to the average GDP growth rate of 1.94 in the sample; the predicted change in GDP growth is 100 x 0.486 / 1.94= 25% of the sample average.</p>
<ul>
<li><p>One possible economic explanation for this is countries that are more engaged in trade as a share of the GDP are more connected to the world and are thus more rapidly able to learn about new technologies and policies that improve a country’s well-being over time relative to countries that are less engaged in international trade and thus less exposed to international best practices among trading partners.</p></li>
<li><p>An alternative explanation is that countries that are more engaged in international trade are better at exploiting the economics of comparative advantage and are thus better at specialising in the production of some products, while relying on trading partners to trade with who separately specialise in the production of other products where they have comparative advantage.<br>
By exploiting production and trading relationships in this way, countries that are more engaged in international trade can use comparative advantage to grow the size of their “economic pie” or GDP relative to more isolated countries that do not exploit the production-enhancing benefits of comparative advantage and trade.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>