<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>ECOM20001 Semester 1 2025   Tutorial 2   Visualising and Describing Data in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="t2_files/libs/clipboard/clipboard.min.js"></script>
<script src="t2_files/libs/quarto-html/quarto.js"></script>
<script src="t2_files/libs/quarto-html/popper.min.js"></script>
<script src="t2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="t2_files/libs/quarto-html/anchor.min.js"></script>
<link href="t2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="t2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="t2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="t2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="t2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="t2_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="t2_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style_rb.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">ECOM20001 Semester 1 2025 <br> Tutorial 2 <br> Visualising and Describing Data in R</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives">Objectives</a></li>
  <li><a href="#part-1-visualising-and-describing-data-in-r" id="toc-part-1-visualising-and-describing-data-in-r" class="nav-link" data-scroll-target="#part-1-visualising-and-describing-data-in-r">Part 1: <br>Visualising and Describing Data in R</a>
  <ul class="collapse">
  <li><a href="#part-a-getting-started" id="toc-part-a-getting-started" class="nav-link" data-scroll-target="#part-a-getting-started">Part A Getting Started</a></li>
  <li><a href="#part-b" id="toc-part-b" class="nav-link" data-scroll-target="#part-b">Part B</a></li>
  <li><a href="#question-b1" id="toc-question-b1" class="nav-link" data-scroll-target="#question-b1">Question B1</a></li>
  <li><a href="#question-b2" id="toc-question-b2" class="nav-link" data-scroll-target="#question-b2">Question B2</a></li>
  <li><a href="#question-b3" id="toc-question-b3" class="nav-link" data-scroll-target="#question-b3">Question B3</a></li>
  </ul></li>
  <li><a href="#part-2-practice-problems" id="toc-part-2-practice-problems" class="nav-link" data-scroll-target="#part-2-practice-problems">Part 2: Practice Problems</a>
  <ul class="collapse">
  <li><a href="#conditional-distributions" id="toc-conditional-distributions" class="nav-link" data-scroll-target="#conditional-distributions">Conditional Distributions</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">Question 1</a></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">Question 2</a></li>
  <li><a href="#part-2-summation" id="toc-part-2-summation" class="nav-link" data-scroll-target="#part-2-summation">Part 2 Summation</a></li>
  </ul></li>
  <li><a href="#optional---expectation-rules" id="toc-optional---expectation-rules" class="nav-link" data-scroll-target="#optional---expectation-rules">Optional - Expectation Rules</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">




<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">Objectives</h2>
<p>After completing this tutorial you should be comfortable with</p>
<ul>
<li><p>Using R to summarise and interpret data</p></li>
<li><p>Creating density plots in R and interpreting these plots</p></li>
<li><p>Creating and interpreting scatter plots in R</p></li>
</ul>
<p>You should also have revisited</p>
<ul>
<li><p>marginal, joint and conditional distributions</p></li>
<li><p>linear transformations of probability distributions</p></li>
<li><p>using Summation and Expectation operators</p></li>
</ul>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>To view the relevant R chunks used to produce the output to answer tutorial questions below click on <span class="math inline">\(\blacktriangleright\)</span> Code in the body text, or <span class="math inline">\(\blacktriangleright\)</span> TRUE in the margin text.</p>
</div>
</div>
</section>
<section id="part-1-visualising-and-describing-data-in-r" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="part-1-visualising-and-describing-data-in-r">Part 1: <br>Visualising and Describing Data in R</h2>
<section id="part-a-getting-started" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="part-a-getting-started">Part A Getting Started</h3>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Tutorial 1 provides details on how to set up the preferred directory structure.</span></div></div>
<p>Please create a Tutorial2 folder on your computer, and then go to the LMS site for ECOM 20001 and download the following files into the Tutorial2 folder:</p>
<ul>
<li><p><strong>tute2.R</strong></p></li>
<li><p><strong>tute2_crime.csv</strong></p></li>
</ul>
<p>The first file is the R code for tutorial 2, the second file is the .csv file that contains the dataset for the tutorial<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. The dataset has the following 5 variables:</p>
<ul>
<li><p><em>stateid</em>: identifier for a US state</p></li>
<li><p><em>vio</em>: violent crime rate — incidents per 100,000 people</p></li>
<li><p><em>rob</em>: robbery rate — incidents per 100,000 people</p></li>
<li><p><em>dens</em>: population per square mile of land</p></li>
<li><p><em>avginc</em>: real per capita personal income in the state</p></li>
</ul>
<p>With the R file and data downloaded into your Tutorial2 folder, you are ready to proceed with the tutorial.<br>
Please go to the <em>tute2.R</em> file to continue with the next 2 sections of the tutorial, which are Visualising Data and Descriptive Statistics.</p>
<p>The first thing to do is set the Working Directory and then load the CSV file into a dataframe:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Set the working directory for the tutorial file</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co">#setwd("/Users/byrned/Dropbox/Teaching/20001/Tutorials/Tutorial2")</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">#..........................</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Note I have not used the line above - use the top menu bar option</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">#..........................</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Load the dataset from a comma separate value</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">read.csv</span>(<span class="at">file=</span><span class="st">"tute2_crime.csv"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the required pacakge(s)</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Before using the <strong>library(stargazer)</strong> command make sure that the package <strong>stargazer</strong> is installed (we went through ways to install packages in Tutorial 1).</p>
<div style="page-break-after: always;"></div>
</section>
<section id="part-b" class="level3">
<h3 class="anchored" data-anchor-id="part-b">Part B</h3>
<p>Having worked through the <em>tute2.R</em> code and graphs, please answer the following:</p>
</section>
<section id="question-b1" class="level3">
<h3 class="anchored" data-anchor-id="question-b1">Question B1</h3>
<p>Discuss the sample means, standard deviations, min and max for each of the four main variables in the dataset: <em>vio</em>, <em>rob</em>, <em>density</em>, <em>avginc</em>.</p>
<ul>
<li>What does a “typical” state look like in the dataset?<br>
Focus on sample means in describing a typical state. Be sure to state the units of a variable to accurately describe what a typical state looks like.</li>
</ul>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## You can also quickly get summary statistics using the summary() and sapply() commands together</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)     <span class="co"># Mean, Min, Max, Median, 25th percentile, 75th percentile</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    stateid        vio             rob             dens             avginc     
 Min.   : 1   Min.   : 66.9   Min.   :  8.8   Min.   :  1.086   Min.   :12.37  
 1st Qu.:12   1st Qu.:275.5   1st Qu.: 75.3   1st Qu.: 34.542   1st Qu.:13.92  
 Median :23   Median :382.8   Median :100.9   Median : 76.529   Median :15.80  
 Mean   :23   Mean   :431.5   Mean   :106.7   Mean   :105.656   Mean   :15.82  
 3rd Qu.:34   3rd Qu.:570.0   3rd Qu.:152.5   3rd Qu.:157.042   3rd Qu.:17.11  
 Max.   :45   Max.   :854.0   Max.   :240.8   Max.   :385.441   Max.   :20.27  </code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(data,sd)   <span class="co"># Standard Deviation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  stateid       vio       rob      dens    avginc 
 13.13393 209.54125  64.19275  97.66395   1.93695 </code></pre>
</div>
</div>
<p>However <strong>stargazer</strong> provides a nicer, more readable table of descriptive statistics:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(data, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">summary.stat =</span> <span class="fu">c</span>(<span class="st">"n"</span>, <span class="st">"mean"</span>, <span class="st">"sd"</span>, <span class="st">"median"</span>, <span class="st">"min"</span>, <span class="st">"max"</span>),  </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">type=</span><span class="st">"text"</span>, <span class="at">title=</span><span class="st">"Descriptive Statistics for the Crime data set"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Descriptive Statistics for the Crime data set
====================================================
Statistic N   Mean   St. Dev. Median   Min     Max  
----------------------------------------------------
stateid   45 23.000   13.134    23      1      45   
vio       45 431.484 209.541  382.800 66.900 854.000
rob       45 106.656  64.193  100.900 8.800  240.800
dens      45 105.656  97.664  76.530  1.086  385.441
avginc    45 15.816   1.937   15.797  12.370 20.273 
----------------------------------------------------</code></pre>
</div>
</div>
<p>Next we have to <strong>interpret</strong> the results (recall the question provided a hint to concentrate on the sample means and use the units provided for each variable).</p>
<p>So we see a <strong>typical</strong> state has: 431 violent crimes per 100,000 people, 107 robberies per 100,000 people, an urban density of 106 people per square mile, and an average annual per-capita income of $15,820 per year.</p>
<ul>
<li>Discuss how the min and max of each variable, highlighting the range of values that each variable takes on.<br>
Just how varied is the degree of violent crimes and robbery rates, and population densities and per capita incomes in the sample?<br>
How violent and robbery-filled is the worst state compared to the best state?</li>
</ul>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The range of robbery and violence rates is remarkable.<br>
Some states have only 67 violent crimes per 100,000 people per year, while others have up to 854 (!) violent crimes per 100,000 people per year.<br>
Its more than 10 times the difference between the least and most violent crime rates across states.<br>
Similarly, the robbery rate is as small as 9 robberies per 100,000 people year and goes up to 240 (!) per 100,000 people per year.</p>
<p>We also have some very rural (1 person per square mile) and urban (385 people per square mile) states.<br>
And per capital income similarly ranges from $12,370 to $20,270.</p>
</section>
<section id="question-b2" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="question-b2">Question B2</h3>
<p>How do the respective probability densities of <em>vio</em>, <em>rob</em>, <em>density</em>, <em>avginc</em> look?</p>
<ul>
<li>Focus on their mean, standard deviation, and skewness</li>
</ul>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Compute probability density for vio and rob variable</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>vio)) </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>rob))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="t2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="t2_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>These do not look very appealing at all!<br>
No title nor axes labels.<br>
In fact, if you used these in an assignment you would <span style="color:red">lose marks</span><br>
So use these code chunks in the R code provided</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Graph histogram of vio, more nicely done</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>vio),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Density of Violent Crimes Rate"</span>,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Violent Crimes Rate per 100,000 People"</span>,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Density"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"orange"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd=</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="t2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># note in this plot the line thickness increases</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># by using the lwd option  - 2 is thicker, 3 is thicker again etc.,</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>You do need to use code such as the above in your assignments if you are asked to produce a density plot.</p>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The following is just provided for interest; there is <strong>no</strong> need to include this in your assignment.</p>
<p>So say, we wanted to include the mean and median for the variable <em>vio</em> in the density plot; we could use</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>vio),</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Density of Violent Crimes Rate"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Violent Crimes Rate per 100,000 People"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Density"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"orange"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd=</span><span class="dv">2</span>)   </span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="do">####  The following is optional you do NOT need to include</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="do">####  these lines in your assignment code</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># to put in the mean add (as a dashed line) use</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">mean</span>(data<span class="sc">$</span>vio),<span class="at">col=</span><span class="st">"red"</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># to put in the median add (as a dashed line e.g. lty=2)</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="fu">median</span>(data<span class="sc">$</span>vio),<span class="at">col=</span><span class="st">"blue"</span>,<span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a><span class="co"># and add a legend </span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="dv">750</span>, <span class="fl">0.0015</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"PDF"</span>, <span class="st">"mean of vio rate"</span>, </span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"median of vio rate"</span>),</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">"orange"</span>, <span class="st">"red"</span>, <span class="st">"blue"</span>), <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">cex=</span><span class="fl">0.8</span>,<span class="at">lwd=</span><span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="t2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</div>
<p>putting together density plots for the variables <em>vio</em>, <em>rob</em>, <em>dens</em> and <em>avginc</em> we have</p>

<div class="no-row-height column-margin column-container"><div class="cell">
<details>
<summary>TRUE</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># code used to generate the density plots</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># displayed together</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>vio),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Density of Violent Crimes Rate"</span>,</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Violent Crimes Rate per 100,000 People"</span>,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Density"</span>,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"orange"</span>,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd=</span><span class="dv">2</span>) </span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>rob),</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Density of Robbery Rate"</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Robberies per 100,000 People"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Density"</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"orange"</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>avginc),</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Per Capita Income (in $000's)"</span>,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Per Capita Income"</span>,</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Density"</span>,</span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"orange"</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(data<span class="sc">$</span>dens),</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Density of People Per Square Mile"</span>,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"People Per Square Mile"</span>,</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Density"</span>,</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"orange"</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div></div><div class="cell">
<div class="cell-output-display">
<p><img src="t2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The urban density variable is right skewed, which means there are many similarly-dense US states, but a few in the right tail of the distribution that are very dense such as New York and California.<br>
The other distributions are relatively symmetric around their means.</p>
</section>
<section id="question-b3" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="question-b3">Question B3</h3>
<p>Comment on the 3 scatter plots listed below; these should be saved in your working directory for tutorial 2.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The required chunks from the R code you were given is below. Note that these are PDF documents; the way to get these is to insert <strong>pdf()</strong> and <em>(insert a file name and extension)</em> before the plot commands which tells R to print to the file and <strong>dev.off()</strong> after the plot commands to tell R to stop writing the output to the file you named.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Robbery and Violent Crime Rate</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pdf</span>(<span class="st">"fig_nice_scatter_rob_vio.pdf"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>vio,data<span class="sc">$</span>rob, </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Relationship Between Robbery Rate and Violent Crime Rate"</span>,</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Violent Crime Rate per 100,000 People"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Robbery Rate per 100,000 People"</span>,</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"blue"</span>,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>() </span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Robbery and Per Capita Income</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">pdf</span>(<span class="st">"fig_nice_scatter_rob_vio.pdf"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>vio,data<span class="sc">$</span>avginc, </span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Relationship Between Robbery Rate and Real Per Personal Capita Income"</span>,</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Violent Crime Rate per 100,000 People"</span>,</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Real Per Personal Capita Income"</span>,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"blue"</span>,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>()</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Violent Crime Rate and Population Density</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a><span class="fu">pdf</span>(<span class="st">"fig_nice_scatter_avginc_vio.pdf"</span>)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(data<span class="sc">$</span>avginc,data<span class="sc">$</span>rob, </span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">"Relationship Between Robbery Rate and Per Capita Income"</span>,</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab=</span><span class="st">"Per Capita Income"</span>,</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"Robery Rate per 100,000 People"</span>,</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"black"</span>,</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch=</span><span class="dv">16</span>)</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a><span class="fu">dev.off</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
</div>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="">Economic explanations focus on the <strong>costs</strong> and <strong>benefits</strong> of a particular behaviour for explaining empirical patterns.</span></div></div>
<p>Visually, does a relationship appear exist in each graph?<br>
If so, offer an <strong>economic explanation</strong> for why the relationship might exist.<br>
There may be multiple explanations, so you may offer various explanations if you wish. But just one explanation is fine.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The scatter plots you created should look like those below:</p>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="t2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="t2_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="t2_files/figure-html/unnamed-chunk-10-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<ul>
<li><p>Perhaps not surprisingly, there is a strong positive correlation between the robbery and violent crime rate.<br>
A natural interpretation is that similar types of people or demographics are likely to engage in robberies and violent crimes which can underlie the strong correlation.</p></li>
<li><p>The relationship between robberies and income is basically non-existent.<br>
Economists commonly refer to a lack of correlation in a scatter plot like this as a <strong>cloud</strong>.<br>
A cloud often results from economic explanations running into each other</p>
<ul>
<li><p>Higher income could mean more benefit on average from robbery, so we should expect a positive relationship between robberies and per capita income</p></li>
<li><p>However, higher income states may have higher tax bases to pay for more effective police forces which makes the cost of robbery higher. This would create a negative relationship between robberies and per capita income. This <em>collision</em> of benefits and costs associated with higher income locations can cause a <strong>cloud</strong> correlation, like we see in the second panel above.</p></li>
</ul></li>
<li><p>Finally, we see a positive relationship between robbery rates and urban density. As the footnote in the tutorial question alluded to, this could potentially reflect:</p>
<ul>
<li><p>The cost of robbery being lower in more dense states as potential robbery targets are more plentiful in close proximity.</p></li>
<li><p>The benefit of robbery being higher if more dense locations attract more retail shops and merchants (called “agglomeration” benefits of urban density), which provides more opportunities and hence benefit for robbery.</p></li>
<li><p>More difficult for police to identify potential robbers in more crowded places, which again makes the expected costs of robbery lower since robbers are less likely to be caught</p></li>
</ul></li>
</ul>
<blockquote class="blockquote">
<p>To be clear: all of these “explanations” are just hypotheses and none of them are proved from a simple scatter plot.<br>
And there are potentially many other hypotheses. Later in ECOM20001, and throughout ECOM30002: Econometrics 2, we develop empirical approaches to unpack these various explanations for correlations found in scatter plots.</p>
</blockquote>
</section>
</section>
<section id="part-2-practice-problems" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="part-2-practice-problems">Part 2: Practice Problems</h2>
<p><em>Note: Part 2 of this tutorial contains extra practice exercises and will potentially only be covered in your tutorial, depending on the time remaining after going through Part 1. You should work through the solutions below and use a consultation to follow up any remaining questions you may have on this material.</em></p>
<section id="conditional-distributions" class="level3">
<h3 class="anchored" data-anchor-id="conditional-distributions">Conditional Distributions</h3>
</section>
<section id="question-1" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="question-1">Question 1</h3>
<p>Suppose you have a random variable <span class="math inline">\(X\)</span> that is i.i.d distributed from a <span class="math inline">\(N(\mu_X,1)\)</span> distribution, and a separate random variable <span class="math inline">\(Y\)</span> that is defined as follows:<br>
<span class="math inline">\(Y=2+2X\)</span></p>
<ol type="a">
<li>What is the distribution of <span class="math inline">\(Y\)</span>?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>The distribution of Y is N<span class="math inline">\(\left(2+2\mu_X,4\right)\)</span>.</p>
<p>How did we get this?</p>
<p>In general (using Expectation outlined in Lecture 2), if one i.i.d. random variable i.e.&nbsp;<span class="math inline">\(Y\)</span> is a linear combination of another i.i.d. variable, <span class="math inline">\(X\)</span> such that <span class="math inline">\(Y=a+bX\)</span> then the mean of <span class="math inline">\(Y\)</span> is <span class="math inline">\(\mu_Y=a+b\mu_X\)</span> and the variance of <span class="math inline">\(Y\)</span> is <span class="math inline">\(\sigma_Y^2 = b^2 \times\sigma_X^2\)</span> . In this case, <span class="math inline">\(a=2\)</span>, <span class="math inline">\(b=2\)</span> and <span class="math inline">\(\sigma_X^2=1\)</span> e.g.&nbsp;<span class="math inline">\(\mu_Y = 2+2\mu_X\)</span> and <span class="math inline">\(\sigma_Y^2 = 2^2 \times 1 = 4\)</span></p>
<ol start="2" type="a">
<li>Graphically plot the conditional distribution of <span class="math inline">\(Y\)</span> if <span class="math inline">\(\mu_X=2,\mu_X=5\)</span>, and if <span class="math inline">\(\mu_X=10\)</span>. What is happening to the conditional distribution of <span class="math inline">\(Y\)</span> for these different <span class="math inline">\(X\)</span> values?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>

<div class="no-row-height column-margin column-container"><div class="">
<p>Plug in the values for <span class="math inline">\(\mu_X\)</span> in the formula above e.g.&nbsp;for <span class="math inline">\(\mu_X=2\)</span>:</p>
<p><span class="math display">\[\mu_Y=2+2\times2=4\]</span></p>
<p><span class="math inline">\(\sigma_Y^2\)</span> remains the same giving.</p>
<p>For <span class="math inline">\(\mu_x=2 \Rightarrow\)</span> <span class="math inline">\(Y \thicksim N(6,4)\)</span></p>
</div></div><p>If <span class="math inline">\(\mu_X\)</span> =2, 5, or 10, then the distribution of <span class="math inline">\(Y\)</span> is <span class="math inline">\(N(6,4)\)</span>, <span class="math inline">\(N(12,4)\)</span>, and <span class="math inline">\(N(22,4)\)</span>, respectively.</p>
<p>The following graph plots the distributions of <span class="math inline">\(Y\)</span>, conditional on the three <span class="math inline">\(\mu_X\)</span> values.<br>
Larger values of <span class="math inline">\(X\)</span> shift the distribution of <span class="math inline">\(Y\)</span> to the right.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="t2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol start="3" type="a">
<li>Suppose Y was instead distributed as <span class="math display">\[Y=2+4X\]</span>.</li>
</ol>
<ul>
<li><p>What is the distribution of <span class="math inline">\(Y\)</span> now?</p></li>
<li><p>Again, graphically plot the conditional distribution of <span class="math inline">\(Y\)</span> if <span class="math inline">\(\mu_X=2\)</span> , if <span class="math inline">\(\mu_X=5\)</span>, and if <span class="math inline">\(\mu_X=10\)</span> and compare your results to what you found in part <strong>b</strong>.</p></li>
<li><p>What can you conclude about the magnitude of how shifts in the conditional distribution of <span class="math inline">\(Y\)</span> as a function of different <span class="math inline">\(X\)</span> values as the magnitude of the slope in the linear function that defines <span class="math inline">\(Y\)</span> increases?</p></li>
</ul>
<p>Note: In answering this question, you may simply draw the conditional distributions of <span class="math inline">\(Y\)</span> by hand, or you may use R to plot the different conditional distributions of <span class="math inline">\(Y\)</span> given <span class="math inline">\(X\)</span>.</p>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>One way of reproducing the plots shown in the solutions in the Subject Home Page on Canvas in R is shown below in the margin notes- there are a <strong>lot</strong> of different ways to do this!.</p>
<p>You will <span style="color:red">not</span> be asked to do this in assignments so you can skip the code below if you wish.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># code used to generate density graphs on the one plot</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>distdat3 <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="at">text =</span> <span class="st">"info mean sd</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="st">mu10 10 4</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="st">mu22 22 4</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="st">mu42 42 4</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="st">"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>densities1 <span class="ot">&lt;-</span> <span class="fu">apply</span>(distdat3[, <span class="sc">-</span><span class="dv">1</span>], <span class="dv">1</span>, <span class="cf">function</span>(x) <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000000</span>, <span class="at">mean =</span> x[<span class="dv">1</span>], <span class="at">sd =</span> x[<span class="dv">2</span>]))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(densities1) <span class="ot">&lt;-</span>distdat3<span class="sc">$</span>info</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>s3<span class="ot">&lt;-</span> <span class="fu">plot</span>(<span class="dv">0</span>, <span class="at">type =</span> <span class="st">"n"</span>, <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">60</span>), <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, .<span class="dv">15</span>),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">"density"</span>, <span class="at">xlab=</span><span class="st">"Y"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (d <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ncol</span>(densities1)){</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lines</span>(<span class="fu">density</span>(densities1[, d]), <span class="at">lty =</span> d,<span class="at">col=</span><span class="st">"black"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topright"</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"N(10,16)"</span>, <span class="st">"N(22,16)"</span> , <span class="st">"N(42,16)"</span>),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">"black"</span>, <span class="st">"red"</span>, <span class="st">"darkgreen"</span>), <span class="at">lty=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">cex=</span><span class="fl">0.8</span>)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a><span class="fu">clip</span>(<span class="dv">0</span>,<span class="dv">10</span>,<span class="dv">0</span>,<span class="fl">0.1</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">10</span>,<span class="at">col=</span><span class="st">"black"</span>,<span class="at">lty=</span><span class="dv">1</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a><span class="fu">clip</span>(<span class="dv">0</span>,<span class="dv">22</span>,<span class="dv">0</span>,<span class="fl">0.1</span>)</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">22</span>, <span class="at">col=</span><span class="st">"red"</span>, <span class="at">lty=</span><span class="dv">2</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="fu">clip</span>(<span class="dv">0</span>,<span class="dv">42</span>,<span class="dv">0</span>,<span class="fl">0.1</span>)</span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">42</span>,<span class="at">col=</span><span class="st">"darkgreen"</span>, <span class="at">lty=</span><span class="dv">3</span>,<span class="at">lwd=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="t2_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The distribution of <span class="math inline">\(Y\)</span> is now N(2+4<span class="math inline">\(\mu_X\)</span>,16).<br>
If <span class="math inline">\(\mu_X\)</span>=2, 5, or 10, then the distribution of <span class="math inline">\(Y\)</span> is now N(10,16), N(22,16), and N(42,16).<br>
There are two key changes in the results from part b. from changing the definition of <span class="math inline">\(Y\)</span> to <span class="math inline">\(Y=2+4X\)</span>.</p>
<ul>
<li><p>The variance of <span class="math inline">\(Y\)</span> increases,</p></li>
<li><p>and the shifts in the mean in the distribution for different <span class="math inline">\(X\)</span> values become larger in magnitude.</p></li>
</ul>
<p>That is, the conditional mean of <span class="math inline">\(Y\)</span> given X becomes more sensitive to changes in <span class="math inline">\(X\)</span>.</p>
</section>
<section id="question-2" class="level3">
<h3 class="anchored" data-anchor-id="question-2">Question 2</h3>
<p>Consider the following table which describes the joint probability distribution for all combinations of studying and performance. The outcome space for Studying (<strong>Y</strong>) and Performance (<strong>X</strong>) is:</p>
<ul>
<li><p><strong>Y</strong> - Studying: Study Hard, Study Sometimes, Study Never</p></li>
<li><p><strong>X</strong> - Performance: High Grade , Medium Grade , Low Grade</p></li>
</ul>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output-display">

<table class="table table-striped" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;">  </th>
   <th style="text-align:right;"> High Grade </th>
   <th style="text-align:right;"> Medium Grade </th>
   <th style="text-align:right;"> Low Grade </th>
   <th style="text-align:right;"> Total </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> Study Hard </td>
   <td style="text-align:right;"> 0.20 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 0.02 </td>
   <td style="text-align:right;"> 0.32 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Sometimes </td>
   <td style="text-align:right;"> 0.07 </td>
   <td style="text-align:right;"> 0.30 </td>
   <td style="text-align:right;"> 0.10 </td>
   <td style="text-align:right;"> 0.47 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Never Study </td>
   <td style="text-align:right;"> 0.01 </td>
   <td style="text-align:right;"> 0.05 </td>
   <td style="text-align:right;"> 0.15 </td>
   <td style="text-align:right;"> 0.21 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> Total </td>
   <td style="text-align:right;"> 0.28 </td>
   <td style="text-align:right;"> 0.45 </td>
   <td style="text-align:right;"> 0.27 </td>
   <td style="text-align:right;"> 1.00 </td>
  </tr>
</tbody>
</table>

</div>
</div>
<ol type="a">
<li>What is the marginal distribution for studying?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<ul>
<li>P(Study Hard)=0.32<br>
</li>
<li>P(Study Sometimes)=0.47<br>
</li>
<li>P(Study Never)=0.21</li>
</ul>
<ol start="2" type="a">
<li>What is the marginal distribution for performance?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<ul>
<li>P(High Grade)=0.28<br>
</li>
<li>P(Medium Grade)=0.45<br>
</li>
<li>P(Low Grade)=0.27</li>
</ul>
<ol start="3" type="a">
<li>What is the probability distribution of Performance, conditional on Studying hard?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<ul>
<li>P(High Grade | Studying Hard)=0.20/0.32=0.625<br>
</li>
<li>P(Medium Grade | Studying Hard)=0.10/0.32=0.3125<br>
</li>
<li>P(Low Grade | Studying Hard)=0.02/0.32=0.0625</li>
</ul>
<ol start="4" type="a">
<li>What is the probability distribution of Performance, conditional on Studying Sometimes?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<ul>
<li>P(High Grade | Studying Sometimes)=0.07/0.47=0.1489<br>
</li>
<li>P(Medium Grade | Studying Sometimes)=0.30/0.47=0.6383<br>
</li>
<li>P(Low Grade | Studying Sometimes)=0.10/0.47=0.2128</li>
</ul>
<ol start="5" type="a">
<li>What is the probability distribution of Studying, conditional on Medium Grade?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<ul>
<li>P(Study Hard | Medium Grade)=0.10/0.45=0.2222<br>
</li>
<li>P(Study Sometimes | Medium Grade)=0.30/0.45=0.6666<br>
</li>
<li>P(Study Never | Medium Grade)=0.05/0.45=0.1111</li>
</ul>
<ol start="6" type="a">
<li>What is the probability distribution of Studying, conditional on Low Grade?</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<ul>
<li>P(Study Hard | Low Grade)=0.02/0.27=0.0741<br>
</li>
<li>P(Study Sometimes | Low Grade)=0.10/0.27=0.3704<br>
</li>
<li>P(Study Never | Low Grade)=0.15/0.27=0.5555</li>
</ul>
<ol start="7" type="a">
<li>Using an example from the table above, show that Studying and Performance are not independently distributed</li>
</ol>
<p><span style="background-color:lightblue;"><strong>Solution</strong></span></p>
<p>If, for example, Studying and Performance were independent, then the joint probability of P(Study Hard, High Grade) would equal the product of the marginal probabilities of Study Hard and High Grade:</p>
<p><strong>P(Study Hard) x P(High Grade)</strong>.<br>
Computing this product we obtain <span class="math inline">\(0.32 \times 0.28 = 0.0896\)</span> which is not equal to the joint probability of</p>
<p><strong>P(Study Hard, High Grade)</strong> in the table of 0.20.<br>
Therefore, Studying and Performance are not independent.</p>
</section>
<section id="part-2-summation" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="part-2-summation">Part 2 Summation</h3>
<p><strong>Summation Practice Problems</strong></p>
<ol type="1">
<li><p>Show the following equality is true<br>
<span class="math display">\[\sum\limits_{i=1}^n\left(x_i-\bar{x} \right)=0\]</span></p></li>
<li><p>Show the following equality is true:<br>
<span class="math display">\[n\bar{x} = \sum\limits_{i}^nx_i\]</span></p></li>
<li><p>Show the following equality is true<br>
<span class="math display">\[\sum\limits_{i=1}^n \left(x_i-\bar{x} \right)^2=\sum\limits_{i=1}^nx_i^2-n\bar{x}^2\]</span></p></li>
<li><p>Show the following equality is true<br>
<span class="math display">\[\sum\limits_{i=1}^n \left(xi-\bar{x}  \right)\left(y_i-\bar{y} \right) = \sum\limits_{i=1}^n x_iy_i - n\bar{x}\bar{y}\]</span></p></li>
</ol>
<p><br></p>
<ol type="1">
<li><p>Derivation</p>
<p><span class="math display">\[\begin{align}
\sum\limits_{i=1}^{n}\left(x_i - \bar{x}   \right) &amp; =  \sum\limits_{i=1}^n {x}_1 -\sum\limits\overline{x} \\
&amp; = \sum\limits_{i=1}^n {x}_i - n {\color{blue}{\overline{x}}} \\
&amp; =  \sum\limits_{i=1}^n {x}_i - n \dfrac{{\color{blue}{\sum\limits_{i=1}^n {x_i}}}}{{\color{blue}{n}}} \\
          &amp; =  \sum\limits_{i=1}^n {x}_i - \sum\limits_{i=1}^n {x}_i = 0
  \end{align}\]</span></p>
</li>
</ol>
<div class="no-row-height column-margin column-container"><div class="">
<p>Run the <span class="math inline">\(\sum\)</span> through</p>
<p><span class="math inline">\(\bar{x}\)</span> is a constant; the sum of a constant is <span class="math inline">\(n*constant\)</span></p>
<p><span class="math inline">\(\bar{x} = \dfrac{\sum x}{n}\)</span></p>
</div></div><p><br></p>
<ol start="2" type="1">
<li><p>Derivation</p>
<p><span class="math display">\[\begin{align}
    n\bar{x}&amp; =\sum\limits_{i=1}^{n} x_i \\
      &amp; = n \dfrac{\sum\limits_{i=1}^n {x_i}}{n} \\
      &amp;  = \sum\limits_{i=1}^n {x_i}
\end{align}\]</span></p>
<p>Notice how you can manipulate summations <span class="math inline">\(\sum\limits_{i=1}^n {x_i}\)</span> and multiply them by <span class="math inline">\(\dfrac{n}{n}\)</span> to get means and sample sizes e.g.&nbsp;:</p></li>
</ol>
<p><span class="math inline">\(\sum\limits_{i=1}^n x_i = \dfrac{n}{n} \sum\limits_{i=1}^n x_i=n \bar{x}_i\)</span></p>
<p><br></p>
<ol start="3" type="1">
<li><p>Derivation<br>
<span class="math display">\[\begin{align*}
\displaystyle \sum\left( x_i - \overline{x}\right)^2 &amp;= \sum \left( x_i^2 - 2\overline x x_i + \overline {x}^2  \right) \\
&amp;= \displaystyle \sum x_i^2  -\sum\left( 2 \overline{x} x_i \right) + \sum\left( \overline {x} ^2 \right) \\
  &amp;= \displaystyle  \sum x_i^2 - 2 \overline  {x } \sum x_i + n \overline {x}^2  \\
&amp;= \displaystyle  \sum x_i^2 - 2 \overline  {x }n \overline {x}+n \overline {x}^2  \\
&amp;=  \displaystyle  \sum x_i^2  - n \overline {x}^2  
\end{align*}\]</span> In line 3, you could also multiply the term <span class="math inline">\(2 \overline {x } \sum x_i\)</span> by <span class="math inline">\(\dfrac{n}{n}\)</span> e.g<br>
multiply by <span class="math inline">\(\dfrac{n}{n} \Rightarrow \displaystyle \sum x_i^2 - 2 n \overline {x } \frac{\sum x_i}{n} + n \overline {x}^2\)</span> which would give the same result as above.</p>

<p><br></p>
<ol start="4" type="1">
<li>Derivation<br>
<span class="math display">\[\begin{align*}
  \displaystyle \sum\left( x_i - \overline {x} \right)\left( y_i - \overline{y} \right)&amp;= \sum \left( x_i y_i -\overline x y_i - \overline {y}x_i+\bar{x} \bar{y}  \right) \\
    &amp;= \displaystyle \sum\left( x_i y_i \right) -\sum\left(  \overline{x} y_i \right) \\  &amp; \quad  - \sum\left( \overline {y} x_i \right)+ \sum\left(\bar{x} \bar{y} \right) \\
&amp;= \displaystyle  \sum x_i y_i -  \overline  {x } \sum y_i -  \overline {y}\sum x_i + n\bar{x} \bar{y} \\
&amp; = \displaystyle \sum x_i y_i - n \bar{x}\bar{y}-n \bar{x}\bar{y} +n \bar{x} \bar{y} \\
&amp;=  \displaystyle  \sum x_i y_i  - n \bar{x} \bar{y}
    \end{align*}\]</span></li>
</ol>
<p>the terms <span class="math inline">\(\bar{x}\sum y_i\)</span> and <span class="math inline">\(\bar{y} \sum x_i\)</span> in the 3<span class="math inline">\(^{\text{rd}}\)</span> line could also be divided by <span class="math inline">\(\dfrac {n} {n}\)</span> yielding the same result. For example:</p></li>
</ol>
<div class="no-row-height column-margin column-container"><div class="">
<p>for 3) and 4):</p>
<p>Expand the term inside the brackets</p>
<p>Run the <span class="math inline">\(\sum\)</span> through term by term</p>
<p>Then use the relevant Expectation Rules and simplify</p>
</div></div><p><span class="math inline">\(\displaystyle \sum x_i y_i - \overline{x } n \frac{\sum y_i}{n} - \overline {y}n \frac{\sum x_i}{n} + n\bar{x} \bar{y}\)</span></p>
<p><br></p>
</section>
</section>
<section id="optional---expectation-rules" class="level2">
<h2 class="anchored" data-anchor-id="optional---expectation-rules">Optional - Expectation Rules</h2>
<p>If <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span> are constants and <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> random variables then:</p>
<ol type="1">
<li><p><span class="math inline">\(E(a)=a\)</span><br>
the expectation of a constant is a constant eg. <span class="math inline">\(E(3)=3\)</span></p></li>
<li><p><span class="math inline">\(E(aX)=a*E(X)\)</span><br>
e.g.&nbsp;if <span class="math inline">\(a=2\)</span> then <span class="math inline">\(E(X)\)</span> doubles</p></li>
<li><p><span class="math inline">\(E(a \pm X)= a \pm E(X)\)</span><br>
e.g.&nbsp;if you add 3 to every case , the expectation will increase by 3</p></li>
<li><p><span class="math inline">\(E(X+Y)= E(X)+E(Y)\)</span><br>
the expectation of a sum = the sum of the expectations</p></li>
<li><p><span class="math inline">\(E(XY) = E(X)*E(Y)\)</span><br>
if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent</p></li>
<li><p><span class="math inline">\(COV(X,Y) = E[(X-E(X))*(Y-E(Y))]= E(XY)-E(X)E(Y)\)</span><br>
if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent then <span class="math inline">\(COV(X,Y)=0\)</span></p></li>
<li><p><span class="math inline">\(V(a)=0\)</span><br>
a constant does not vary e.g.&nbsp;<span class="math inline">\(V(7)=0\)</span></p></li>
<li><p><span class="math inline">\(V(a \pm X)=V(X)\)</span><br>
this follows from point 7. above</p></li>
<li><p><span class="math inline">\(V(a \pm b X) = V(a)+b^2 V(X) = b^2 V(X)\)</span><br>
a constant is squared when taken outside a variance operator (also use point 7.)</p></li>
<li><p><span class="math inline">\(V(X \pm Y = V(x) + V(Y) \pm 2*COV(X,Y)\)</span><br>
using point 6. if <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are independent then <span class="math inline">\(V(X \pm Y) = V(X) + V(Y)\)</span></p></li>
</ol>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>The reference research article for these data is: Donohue, J. , Ayres, I. (2003) “Shooting Down the ‘More Guns Less Crime’ Hypothesis”, Stanford Law Review, 55, pp.&nbsp;1193-1312<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>